// Code generated by supermetal-inc/terraform-provider-gen@6a2b361, spec v0.1.10. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// =============================================================================
// BigQuerySink Models
// =============================================================================

type BigQuerySinkModel struct {
	Auth                *BigqueryAuthModel         `tfsdk:"auth"`
	Dataset             types.String               `tfsdk:"dataset"`
	DisableSchemaPrefix types.Bool                 `tfsdk:"disable_schema_prefix"`
	HistoryMode         *MigrationHistoryModeModel `tfsdk:"history_mode"`
	MigrationStrategy   *MigrationStrategyModel    `tfsdk:"migration_strategy"`
	ProjectID           types.String               `tfsdk:"project_id"`
	QueryPriority       types.String               `tfsdk:"query_priority"`
	WriteMode           *BigqueryWriteModeModel    `tfsdk:"write_mode"`
}

type BigqueryAuthModel struct {
	ServiceAccountKey *BigqueryServiceAccountKeyModel `tfsdk:"service_account_key"`
}

type BigqueryServiceAccountKeyModel struct {
	KeyJSON types.String `tfsdk:"key_json"`
}

type MigrationHistoryModeModel struct {
	Append *MigrationAppendHistoryModel `tfsdk:"append"`
}

type MigrationAppendHistoryModel struct {
	Suffix types.String `tfsdk:"suffix"`
}

type MigrationStrategyModel struct {
	Allowed    types.List `tfsdk:"allowed"`
	DisableAll types.Bool `tfsdk:"disable_all"`
}

type BigqueryWriteModeModel struct {
	Merge           *BigqueryMergeModel           `tfsdk:"merge"`
	StorageWriteAPI *BigqueryStorageWriteApiModel `tfsdk:"storage_write_api"`
}

type BigqueryMergeModel struct {
	UseTransactions types.Bool `tfsdk:"use_transactions"`
}

type BigqueryStorageWriteApiModel struct {
	MaxStalenessMinutes types.Int32 `tfsdk:"max_staleness_minutes"`
}

// =============================================================================
// ClickhouseSink Models
// =============================================================================

type ClickhouseSinkModel struct {
	AsyncInserts              types.Bool                        `tfsdk:"async_inserts"`
	HTTPURL                   types.String                      `tfsdk:"http_url"`
	Password                  types.String                      `tfsdk:"password"`
	SslClientCertPEM          types.String                      `tfsdk:"ssl_client_cert_pem"`
	SslClientKeyPEM           types.String                      `tfsdk:"ssl_client_key_pem"`
	SslRootCert               types.String                      `tfsdk:"ssl_root_cert"`
	SslVerify                 types.Bool                        `tfsdk:"ssl_verify"`
	User                      types.String                      `tfsdk:"user"`
	DisableSchemaPrefix       types.Bool                        `tfsdk:"disable_schema_prefix"`
	Engine                    types.String                      `tfsdk:"engine"`
	HistoryMode               *MigrationHistoryModeModel        `tfsdk:"history_mode"`
	MaxSnapshotConcurrency    types.Int32                       `tfsdk:"max_snapshot_concurrency"`
	MigrationStrategy         *MigrationStrategyModel           `tfsdk:"migration_strategy"`
	NonNullableColumns        types.Bool                        `tfsdk:"non_nullable_columns"`
	PreserveSourceNullability types.Bool                        `tfsdk:"preserve_source_nullability"`
	TableNameModifier         *ClickhouseTableNameModifierModel `tfsdk:"table_name_modifier"`
	TargetDatabase            types.String                      `tfsdk:"target_database"`
	TtlDays                   types.Int32                       `tfsdk:"ttl_days"`
}

type ClickhouseTableNameModifierModel struct {
	Suffix *ClickhouseCustomSuffixModel `tfsdk:"suffix"`
	Prefix *ClickhouseCustomPrefixModel `tfsdk:"prefix"`
}

type ClickhouseCustomSuffixModel struct {
	Value types.String `tfsdk:"value"`
}

type ClickhouseCustomPrefixModel struct {
	Value types.String `tfsdk:"value"`
}

// =============================================================================
// DatabricksSink Models
// =============================================================================

type DatabricksSinkModel struct {
	Auth              *DatabricksAuthModel          `tfsdk:"auth"`
	HistoryMode       *MigrationHistoryModeModel    `tfsdk:"history_mode"`
	MigrationStrategy *MigrationStrategyModel       `tfsdk:"migration_strategy"`
	StorageCredential types.String                  `tfsdk:"storage_credential"`
	TableFeatures     *DatabricksTableFeaturesModel `tfsdk:"table_features"`
	TargetCatalog     types.String                  `tfsdk:"target_catalog"`
	TargetSchema      types.String                  `tfsdk:"target_schema"`
	Volume            types.String                  `tfsdk:"volume"`
	Warehouse         types.String                  `tfsdk:"warehouse"`
}

type DatabricksAuthModel struct {
	Cli *DatabricksCliAuthModel `tfsdk:"cli"`
	Pat *DatabricksPatAuthModel `tfsdk:"pat"`
	M2m *DatabricksM2mAuthModel `tfsdk:"m2m"`
}

type DatabricksCliAuthModel struct {
}

type DatabricksPatAuthModel struct {
	PersonalAccessToken types.String `tfsdk:"personal_access_token"`
	WorkspaceHost       types.String `tfsdk:"workspace_host"`
}

type DatabricksM2mAuthModel struct {
	ClientID      types.String `tfsdk:"client_id"`
	ClientSecret  types.String `tfsdk:"client_secret"`
	WorkspaceHost types.String `tfsdk:"workspace_host"`
}

type DatabricksTableFeaturesModel struct {
	DeletionVectors types.Bool `tfsdk:"deletion_vectors"`
	DeltaUniform    types.Bool `tfsdk:"delta_uniform"`
	TypeWidening    types.Bool `tfsdk:"type_widening"`
}

// =============================================================================
// Db2Source Models
// =============================================================================

type Db2SourceModel struct {
	Catalog              *CatalogModel                       `tfsdk:"catalog"`
	Database             types.String                        `tfsdk:"database"`
	Host                 types.String                        `tfsdk:"host"`
	MaxPoolSize          types.Int32                         `tfsdk:"max_pool_size"`
	Password             types.String                        `tfsdk:"password"`
	Port                 types.Int32                         `tfsdk:"port"`
	User                 types.String                        `tfsdk:"user"`
	KeylessTableStrategy *MigrationKeylessTableStrategyModel `tfsdk:"keyless_table_strategy"`
	ReplicationType      *Db2ReplicationTypeModel            `tfsdk:"replication_type"`
	SystemColumns        *MigrationSystemColumnsModel        `tfsdk:"system_columns"`
}

type CatalogModel struct {
	DefaultAction types.String                   `tfsdk:"default_action"`
	Name          types.String                   `tfsdk:"name"`
	Schemas       map[string]*CatalogSchemaModel `tfsdk:"schemas"`
}

type CatalogSchemaModel struct {
	Action types.String                  `tfsdk:"action"`
	Tables map[string]*CatalogTableModel `tfsdk:"tables"`
}

type CatalogTableModel struct {
	Action               types.String                   `tfsdk:"action"`
	Columns              map[string]*CatalogColumnModel `tfsdk:"columns"`
	IcebergPartitionSpec *IcebergPartitionSpecModel     `tfsdk:"iceberg_partition_spec"`
}

type CatalogColumnModel struct {
	Action types.String `tfsdk:"action"`
}

type IcebergPartitionSpecModel struct {
	Fields []*IcebergPartitionFieldModel `tfsdk:"fields"`
}

type IcebergPartitionFieldModel struct {
	Name         types.String           `tfsdk:"name"`
	SourceColumn types.String           `tfsdk:"source_column"`
	Transform    *IcebergTransformModel `tfsdk:"transform"`
}

type IcebergTransformModel struct {
	Identity *IcebergIdentityTransformModel `tfsdk:"identity"`
	Year     *IcebergYearTransformModel     `tfsdk:"year"`
	Month    *IcebergMonthTransformModel    `tfsdk:"month"`
	Day      *IcebergDayTransformModel      `tfsdk:"day"`
	Hour     *IcebergHourTransformModel     `tfsdk:"hour"`
	Bucket   *IcebergBucketTransformModel   `tfsdk:"bucket"`
	Truncate *IcebergTruncateTransformModel `tfsdk:"truncate"`
}

type IcebergIdentityTransformModel struct {
}

type IcebergYearTransformModel struct {
}

type IcebergMonthTransformModel struct {
}

type IcebergDayTransformModel struct {
}

type IcebergHourTransformModel struct {
}

type IcebergBucketTransformModel struct {
	NumBuckets types.Int32 `tfsdk:"num_buckets"`
}

type IcebergTruncateTransformModel struct {
	Width types.Int32 `tfsdk:"width"`
}

type MigrationKeylessTableStrategyModel struct {
	AppendOnly     *MigrationAppendOnlyModel     `tfsdk:"append_only"`
	DedupByRowHash *MigrationDedupByRowHashModel `tfsdk:"dedup_by_row_hash"`
}

type MigrationAppendOnlyModel struct {
}

type MigrationDedupByRowHashModel struct {
}

type Db2ReplicationTypeModel struct {
	Snapshot *Db2SnapshotModel `tfsdk:"snapshot"`
}

type Db2SnapshotModel struct {
	MaxTextSize types.Int32 `tfsdk:"max_text_size"`
}

type MigrationSystemColumnsModel struct {
	Lsn      *MigrationLsnModel      `tfsdk:"lsn"`
	Op       *MigrationOpModel       `tfsdk:"op"`
	SyncedAt *MigrationSyncedAtModel `tfsdk:"synced_at"`
}

type MigrationLsnModel struct {
}

type MigrationOpModel struct {
	Encoding       types.String `tfsdk:"encoding"`
	SnapshotAsRead types.Bool   `tfsdk:"snapshot_as_read"`
}

type MigrationSyncedAtModel struct {
}

// =============================================================================
// DorisSink Models
// =============================================================================

type DorisSinkModel struct {
	BinaryHandlingMode        types.String                 `tfsdk:"binary_handling_mode"`
	FeHTTPURL                 types.String                 `tfsdk:"fe_http_url"`
	FeMysqlPoolMax            types.Int32                  `tfsdk:"fe_mysql_pool_max"`
	FeMysqlPort               types.Int32                  `tfsdk:"fe_mysql_port"`
	Password                  types.String                 `tfsdk:"password"`
	SslClientCertPEM          types.String                 `tfsdk:"ssl_client_cert_pem"`
	SslClientKeyPEM           types.String                 `tfsdk:"ssl_client_key_pem"`
	SslRootCert               types.String                 `tfsdk:"ssl_root_cert"`
	SslVerify                 types.Bool                   `tfsdk:"ssl_verify"`
	User                      types.String                 `tfsdk:"user"`
	DisableSchemaPrefix       types.Bool                   `tfsdk:"disable_schema_prefix"`
	HistoryMode               *MigrationHistoryModeModel   `tfsdk:"history_mode"`
	MaxSnapshotConcurrency    types.Int32                  `tfsdk:"max_snapshot_concurrency"`
	MigrationStrategy         *MigrationStrategyModel      `tfsdk:"migration_strategy"`
	PreserveSourceNullability types.Bool                   `tfsdk:"preserve_source_nullability"`
	TableModel                types.String                 `tfsdk:"table_model"`
	TableNameModifier         *DorisTableNameModifierModel `tfsdk:"table_name_modifier"`
	TargetDatabase            types.String                 `tfsdk:"target_database"`
}

type DorisTableNameModifierModel struct {
	Suffix *DorisCustomSuffixModel `tfsdk:"suffix"`
	Prefix *DorisCustomPrefixModel `tfsdk:"prefix"`
}

type DorisCustomSuffixModel struct {
	Value types.String `tfsdk:"value"`
}

type DorisCustomPrefixModel struct {
	Value types.String `tfsdk:"value"`
}

// =============================================================================
// DuckDBSink Models
// =============================================================================

type DuckDBSinkModel struct {
	Connection                *DuckdbConnectionModel     `tfsdk:"connection"`
	EnablePrimaryKeys         types.Bool                 `tfsdk:"enable_primary_keys"`
	HistoryMode               *MigrationHistoryModeModel `tfsdk:"history_mode"`
	MaxSnapshotConcurrency    types.Int32                `tfsdk:"max_snapshot_concurrency"`
	MigrationStrategy         *MigrationStrategyModel    `tfsdk:"migration_strategy"`
	PreserveSourceNullability types.Bool                 `tfsdk:"preserve_source_nullability"`
	TargetDatabase            types.String               `tfsdk:"target_database"`
	TargetSchema              types.String               `tfsdk:"target_schema"`
	UseTransactions           types.Bool                 `tfsdk:"use_transactions"`
}

type DuckdbConnectionModel struct {
	Quack *DuckdbQuackModel `tfsdk:"quack"`
	Pg    *PostgresModel    `tfsdk:"pg"`
}

type DuckdbQuackModel struct {
	Ssl   types.Bool   `tfsdk:"ssl"`
	Token types.String `tfsdk:"token"`
	URL   types.String `tfsdk:"url"`
}

type PostgresModel struct {
	Database                    types.String        `tfsdk:"database"`
	Host                        types.String        `tfsdk:"host"`
	MaxPoolSize                 types.Int64         `tfsdk:"max_pool_size"`
	OperationLockTimeoutSeconds types.Int32         `tfsdk:"operation_lock_timeout_seconds"`
	Password                    types.String        `tfsdk:"password"`
	Port                        types.Int32         `tfsdk:"port"`
	SslCert                     types.String        `tfsdk:"ssl_cert"`
	SslKey                      types.String        `tfsdk:"ssl_key"`
	SslMode                     types.String        `tfsdk:"ssl_mode"`
	SslRootCert                 types.String        `tfsdk:"ssl_root_cert"`
	Tunnel                      *SshTunnelTypeModel `tfsdk:"tunnel"`
	User                        types.String        `tfsdk:"user"`
}

type SshTunnelTypeModel struct {
	Ssh *SshTunnelModel `tfsdk:"ssh"`
}

type SshTunnelModel struct {
	Auth              *SshAuthModel `tfsdk:"auth"`
	BastionAlternates types.List    `tfsdk:"bastion_alternates"`
	BastionHost       types.String  `tfsdk:"bastion_host"`
	BastionPort       types.Int32   `tfsdk:"bastion_port"`
	User              types.String  `tfsdk:"user"`
}

type SshAuthModel struct {
	GeneratedKey    *SshGeneratedKeyModel    `tfsdk:"generated_key"`
	BringYourOwnKey *SshBringYourOwnKeyModel `tfsdk:"bring_your_own_key"`
}

type SshGeneratedKeyModel struct {
	PrivateKey types.String `tfsdk:"private_key"`
	PublicKey  types.String `tfsdk:"public_key"`
}

type SshBringYourOwnKeyModel struct {
	PrivateKey types.String `tfsdk:"private_key"`
}

// =============================================================================
// FileSource Models
// =============================================================================

type FileSourceModel struct {
	Discovery       *FileDiscoveryModel          `tfsdk:"discovery"`
	ErrorHandling   *FileErrorHandlingModel      `tfsdk:"error_handling"`
	ExcludePatterns types.List                   `tfsdk:"exclude_patterns"`
	FormatDetails   *BufferFormatDetailsModel    `tfsdk:"format_details"`
	GlobPatterns    types.List                   `tfsdk:"glob_patterns"`
	ObjectStore     *BufferObjectStoreModel      `tfsdk:"object_store"`
	PostProcessing  *FilePostProcessingModel     `tfsdk:"post_processing"`
	StartDate       types.Int64                  `tfsdk:"start_date"`
	SystemColumns   *MigrationSystemColumnsModel `tfsdk:"system_columns"`
	TableMapping    *FileTableMappingModel       `tfsdk:"table_mapping"`
}

type FileDiscoveryModel struct {
	Poll *FilePollModel `tfsdk:"poll"`
}

type FilePollModel struct {
	IntervalSeconds types.Int64 `tfsdk:"interval_seconds"`
}

type FileErrorHandlingModel struct {
	OnFileError types.String `tfsdk:"on_file_error"`
}

type BufferFormatDetailsModel struct {
	Csv     *BufferCsvFormatModel     `tfsdk:"csv"`
	JSON    *BufferJsonFormatModel    `tfsdk:"json"`
	Parquet *BufferParquetFormatModel `tfsdk:"parquet"`
}

type BufferCsvFormatModel struct {
	AllowJaggedRows types.Bool   `tfsdk:"allow_jagged_rows"`
	Comment         types.String `tfsdk:"comment"`
	Delimiter       types.String `tfsdk:"delimiter"`
	Encoding        types.String `tfsdk:"encoding"`
	Escape          types.String `tfsdk:"escape"`
	HasHeader       types.Bool   `tfsdk:"has_header"`
	NullValues      types.List   `tfsdk:"null_values"`
	Quote           types.String `tfsdk:"quote"`
	SkipRows        types.Int32  `tfsdk:"skip_rows"`
	Terminator      types.String `tfsdk:"terminator"`
}

type BufferJsonFormatModel struct {
	Flatten         types.Bool `tfsdk:"flatten"`
	MultiLine       types.Bool `tfsdk:"multi_line"`
	StripOuterArray types.Bool `tfsdk:"strip_outer_array"`
}

type BufferParquetFormatModel struct {
	BinaryAsText types.Bool `tfsdk:"binary_as_text"`
}

type BufferObjectStoreModel struct {
	AllowHTTP                types.Bool                    `tfsdk:"allow_http"`
	AllowInvalidCertificates types.Bool                    `tfsdk:"allow_invalid_certificates"`
	MaxConcurrentParts       types.Int32                   `tfsdk:"max_concurrent_parts"`
	MaxConcurrentRequests    types.Int32                   `tfsdk:"max_concurrent_requests"`
	Options                  map[string]*BufferOptionModel `tfsdk:"options"`
	RootCertificatePEM       types.String                  `tfsdk:"root_certificate_pem"`
	URL                      types.String                  `tfsdk:"url"`
}

type BufferOptionModel struct {
	Value types.String `tfsdk:"value"`
}

type FilePostProcessingModel struct {
	Delete *FileDeleteAfterProcessingModel `tfsdk:"delete"`
	Move   *FileMoveAfterProcessingModel   `tfsdk:"move"`
}

type FileDeleteAfterProcessingModel struct {
}

type FileMoveAfterProcessingModel struct {
	Destination types.String `tfsdk:"destination"`
}

type FileTableMappingModel struct {
	Single  *FileSingleTableMappingModel  `tfsdk:"single"`
	Auto    *FileAutoTableMappingModel    `tfsdk:"auto"`
	Dynamic *FileDynamicTableMappingModel `tfsdk:"dynamic"`
}

type FileSingleTableMappingModel struct {
	Destination types.String `tfsdk:"destination"`
}

type FileAutoTableMappingModel struct {
	Prefix types.String `tfsdk:"prefix"`
	Suffix types.String `tfsdk:"suffix"`
}

type FileDynamicTableMappingModel struct {
	Pattern  types.String `tfsdk:"pattern"`
	Template types.String `tfsdk:"template"`
}

// =============================================================================
// IcebergSink Models
// =============================================================================

type IcebergSinkModel struct {
	Catalog               *IcebergCatalogModel               `tfsdk:"catalog"`
	MaxCatalogConcurrency types.Int32                        `tfsdk:"max_catalog_concurrency"`
	MetadataCompression   types.String                       `tfsdk:"metadata_compression"`
	MigrationStrategy     *MigrationStrategyModel            `tfsdk:"migration_strategy"`
	Parquet               *IcebergParquetWriterSettingsModel `tfsdk:"parquet"`
	SpecVersion           types.String                       `tfsdk:"spec_version"`
	StorageCredentials    *IcebergStorageCredentialsModel    `tfsdk:"storage_credentials"`
	TargetNamespace       types.List                         `tfsdk:"target_namespace"`
	TruncateTableIfExists types.Bool                         `tfsdk:"truncate_table_if_exists"`
	TypeConversion        *MigrationTypeConversionModel      `tfsdk:"type_conversion"`
	VendedCredentials     types.Bool                         `tfsdk:"vended_credentials"`
	WriteMode             *IcebergWriteModeModel             `tfsdk:"write_mode"`
}

type IcebergCatalogModel struct {
	Rest      *IcebergRestCatalogModel      `tfsdk:"rest"`
	Glue      *IcebergGlueCatalogModel      `tfsdk:"glue"`
	Hms       *IcebergHmsCatalogModel       `tfsdk:"hms"`
	S3tables  *IcebergS3TablesCatalogModel  `tfsdk:"s3tables"`
	Sql       *IcebergSqlCatalogModel       `tfsdk:"sql"`
	Snowflake *IcebergSnowflakeCatalogModel `tfsdk:"snowflake"`
	Unity     *IcebergUnityCatalogModel     `tfsdk:"unity"`
}

type IcebergRestCatalogModel struct {
	Auth       *IcebergCatalogAuthModel `tfsdk:"auth"`
	Properties []*IcebergPropertyModel  `tfsdk:"properties"`
	URI        types.String             `tfsdk:"uri"`
	Warehouse  types.String             `tfsdk:"warehouse"`
}

type IcebergCatalogAuthModel struct {
	Oauth2 *IcebergOAuth2AuthModel `tfsdk:"oauth2"`
	Bearer *IcebergBearerAuthModel `tfsdk:"bearer"`
	Basic  *IcebergBasicAuthModel  `tfsdk:"basic"`
	Sigv4  *IcebergSigV4AuthModel  `tfsdk:"sigv4"`
}

type IcebergOAuth2AuthModel struct {
	ClientID      types.String `tfsdk:"client_id"`
	ClientSecret  types.String `tfsdk:"client_secret"`
	Scope         types.String `tfsdk:"scope"`
	TokenEndpoint types.String `tfsdk:"token_endpoint"`
}

type IcebergBearerAuthModel struct {
	Token types.String `tfsdk:"token"`
}

type IcebergBasicAuthModel struct {
	Password types.String `tfsdk:"password"`
	Username types.String `tfsdk:"username"`
}

type IcebergSigV4AuthModel struct {
	AccessKeyID     types.String `tfsdk:"access_key_id"`
	ProfileName     types.String `tfsdk:"profile_name"`
	Region          types.String `tfsdk:"region"`
	SecretAccessKey types.String `tfsdk:"secret_access_key"`
	Service         types.String `tfsdk:"service"`
	SessionToken    types.String `tfsdk:"session_token"`
}

type IcebergPropertyModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

type IcebergGlueCatalogModel struct {
	AccessKeyID     types.String            `tfsdk:"access_key_id"`
	CatalogID       types.String            `tfsdk:"catalog_id"`
	ProfileName     types.String            `tfsdk:"profile_name"`
	Properties      []*IcebergPropertyModel `tfsdk:"properties"`
	Region          types.String            `tfsdk:"region"`
	SecretAccessKey types.String            `tfsdk:"secret_access_key"`
	SessionToken    types.String            `tfsdk:"session_token"`
	URI             types.String            `tfsdk:"uri"`
	Warehouse       types.String            `tfsdk:"warehouse"`
}

type IcebergHmsCatalogModel struct {
	Properties      []*IcebergPropertyModel `tfsdk:"properties"`
	ThriftTransport types.String            `tfsdk:"thrift_transport"`
	URI             types.String            `tfsdk:"uri"`
	Warehouse       types.String            `tfsdk:"warehouse"`
}

type IcebergS3TablesCatalogModel struct {
	AccessKeyID     types.String            `tfsdk:"access_key_id"`
	Endpoint        types.String            `tfsdk:"endpoint"`
	ProfileName     types.String            `tfsdk:"profile_name"`
	Properties      []*IcebergPropertyModel `tfsdk:"properties"`
	Region          types.String            `tfsdk:"region"`
	SecretAccessKey types.String            `tfsdk:"secret_access_key"`
	SessionToken    types.String            `tfsdk:"session_token"`
	TableBucketArn  types.String            `tfsdk:"table_bucket_arn"`
}

type IcebergSqlCatalogModel struct {
	BindStyle  types.String            `tfsdk:"bind_style"`
	Properties []*IcebergPropertyModel `tfsdk:"properties"`
	URI        types.String            `tfsdk:"uri"`
	Warehouse  types.String            `tfsdk:"warehouse"`
}

type IcebergSnowflakeCatalogModel struct {
	Database   types.String            `tfsdk:"database"`
	Password   types.String            `tfsdk:"password"`
	Properties []*IcebergPropertyModel `tfsdk:"properties"`
	Role       types.String            `tfsdk:"role"`
	Schema     types.String            `tfsdk:"schema"`
	URI        types.String            `tfsdk:"uri"`
	Username   types.String            `tfsdk:"username"`
	Warehouse  types.String            `tfsdk:"warehouse"`
}

type IcebergUnityCatalogModel struct {
	CatalogName types.String            `tfsdk:"catalog_name"`
	Properties  []*IcebergPropertyModel `tfsdk:"properties"`
	Token       types.String            `tfsdk:"token"`
	URI         types.String            `tfsdk:"uri"`
}

type IcebergParquetWriterSettingsModel struct {
	Compression      types.String `tfsdk:"compression"`
	CompressionLevel types.Int32  `tfsdk:"compression_level"`
	TargetFileSizeMb types.Int32  `tfsdk:"target_file_size_mb"`
	Version          types.String `tfsdk:"version"`
}

type IcebergStorageCredentialsModel struct {
	S3     *IcebergS3CredentialsModel     `tfsdk:"s3"`
	Gcs    *IcebergGcsCredentialsModel    `tfsdk:"gcs"`
	Azure  *IcebergAzureCredentialsModel  `tfsdk:"azure"`
	Custom *IcebergCustomCredentialsModel `tfsdk:"custom"`
}

type IcebergS3CredentialsModel struct {
	AccessKeyID     types.String            `tfsdk:"access_key_id"`
	Endpoint        types.String            `tfsdk:"endpoint"`
	IamRoleArn      types.String            `tfsdk:"iam_role_arn"`
	PathStyleAccess types.Bool              `tfsdk:"path_style_access"`
	ProfileName     types.String            `tfsdk:"profile_name"`
	Properties      []*IcebergPropertyModel `tfsdk:"properties"`
	Region          types.String            `tfsdk:"region"`
	SecretAccessKey types.String            `tfsdk:"secret_access_key"`
	SessionToken    types.String            `tfsdk:"session_token"`
}

type IcebergGcsCredentialsModel struct {
	CredentialsJSON types.String            `tfsdk:"credentials_json"`
	ProjectID       types.String            `tfsdk:"project_id"`
	Properties      []*IcebergPropertyModel `tfsdk:"properties"`
}

type IcebergAzureCredentialsModel struct {
	AccountKey   types.String            `tfsdk:"account_key"`
	AccountName  types.String            `tfsdk:"account_name"`
	ClientID     types.String            `tfsdk:"client_id"`
	ClientSecret types.String            `tfsdk:"client_secret"`
	Endpoint     types.String            `tfsdk:"endpoint"`
	Properties   []*IcebergPropertyModel `tfsdk:"properties"`
	TenantID     types.String            `tfsdk:"tenant_id"`
}

type IcebergCustomCredentialsModel struct {
	Properties []*IcebergPropertyModel `tfsdk:"properties"`
}

type MigrationTypeConversionModel struct {
	Nanosecond *MigrationNanosecondModel `tfsdk:"nanosecond"`
	Numeric    *MigrationNumericModel    `tfsdk:"numeric"`
}

type MigrationNanosecondModel struct {
	Mode types.String `tfsdk:"mode"`
}

type MigrationNumericModel struct {
	Mode      types.String `tfsdk:"mode"`
	Precision types.Int32  `tfsdk:"precision"`
	Scale     types.Int32  `tfsdk:"scale"`
}

type IcebergWriteModeModel struct {
	Append      *IcebergAppendModel      `tfsdk:"append"`
	MergeOnRead *IcebergMergeOnReadModel `tfsdk:"merge_on_read"`
}

type IcebergAppendModel struct {
}

type IcebergMergeOnReadModel struct {
	DeleteMode               types.String               `tfsdk:"delete_mode"`
	HistoryMode              *MigrationHistoryModeModel `tfsdk:"history_mode"`
	UsePositionalDeletesOnly types.Bool                 `tfsdk:"use_positional_deletes_only"`
}

// =============================================================================
// KafkaSink Models
// =============================================================================

type KafkaSinkModel struct {
	Connection        *KafkaModel             `tfsdk:"connection"`
	Format            *KaformatModel          `tfsdk:"format"`
	Name              types.String            `tfsdk:"name"`
	TopicNameTemplate types.String            `tfsdk:"topic_name_template"`
	TopicOptions      *KafkaTopicOptionsModel `tfsdk:"topic_options"`
}

type KafkaModel struct {
	Auth    *KafkaAuthModel         `tfsdk:"auth"`
	Brokers types.List              `tfsdk:"brokers"`
	Config  *KafkaClientConfigModel `tfsdk:"config"`
}

type KafkaAuthModel struct {
	Mechanism              types.String `tfsdk:"mechanism"`
	Password               types.String `tfsdk:"password"`
	Protocol               types.String `tfsdk:"protocol"`
	SslCALocation          types.String `tfsdk:"ssl_ca_location"`
	SslCertificateLocation types.String `tfsdk:"ssl_certificate_location"`
	SslKeyLocation         types.String `tfsdk:"ssl_key_location"`
	SslKeyPassword         types.String `tfsdk:"ssl_key_password"`
	Username               types.String `tfsdk:"username"`
}

type KafkaClientConfigModel struct {
	Acks                           types.String                 `tfsdk:"acks"`
	BatchSize                      types.Int32                  `tfsdk:"batch_size"`
	ClientID                       types.String                 `tfsdk:"client_id"`
	CompressionType                types.String                 `tfsdk:"compression_type"`
	EnableIdempotence              types.Bool                   `tfsdk:"enable_idempotence"`
	GlobalProperties               []*KafkaPropertyModel        `tfsdk:"global_properties"`
	LingerMs                       types.Int32                  `tfsdk:"linger_ms"`
	MessageMaxBytes                types.Int32                  `tfsdk:"message_max_bytes"`
	MessageSendMaxRetries          types.Int32                  `tfsdk:"message_send_max_retries"`
	MessageTimeoutMs               types.Int32                  `tfsdk:"message_timeout_ms"`
	Partitioner                    types.String                 `tfsdk:"partitioner"`
	ProducerPoolSize               types.Int32                  `tfsdk:"producer_pool_size"`
	ProducerPreset                 types.String                 `tfsdk:"producer_preset"`
	ProducerProperties             []*KafkaPropertyModel        `tfsdk:"producer_properties"`
	QueueBufferingMaxKbytes        types.Int32                  `tfsdk:"queue_buffering_max_kbytes"`
	QueueBufferingMaxMessages      types.Int32                  `tfsdk:"queue_buffering_max_messages"`
	RetryBackoffMaxMs              types.Int32                  `tfsdk:"retry_backoff_max_ms"`
	RetryBackoffMs                 types.Int32                  `tfsdk:"retry_backoff_ms"`
	ShutdownFlushTimeoutMs         types.Int64                  `tfsdk:"shutdown_flush_timeout_ms"`
	TimeoutMs                      types.Int64                  `tfsdk:"timeout_ms"`
	TopicMetadataRefreshIntervalMs types.Int64                  `tfsdk:"topic_metadata_refresh_interval_ms"`
	Transactions                   *KafkaTransactionConfigModel `tfsdk:"transactions"`
}

type KafkaPropertyModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

type KafkaTransactionConfigModel struct {
	Enabled         types.Bool   `tfsdk:"enabled"`
	OpTimeoutMs     types.Int32  `tfsdk:"op_timeout_ms"`
	TimeoutMs       types.Int32  `tfsdk:"timeout_ms"`
	TransactionalID types.String `tfsdk:"transactional_id"`
}

type KaformatModel struct {
	Debezium   *KafkaDebeziumFormatModel   `tfsdk:"debezium"`
	Supermetal *KafkaSupermetalFormatModel `tfsdk:"supermetal"`
}

type KafkaDebeziumFormatModel struct {
	DataTypes          *KafkaDataTypeConfigModel       `tfsdk:"data_types"`
	EmitTxMetadata     types.Bool                      `tfsdk:"emit_tx_metadata"`
	FormatConfig       *KaformatConfigModel            `tfsdk:"format_config"`
	Headers            *KafkaDebeziumHeaderConfigModel `tfsdk:"headers"`
	IncludeBefore      types.Bool                      `tfsdk:"include_before"`
	SkippedOperations  types.String                    `tfsdk:"skipped_operations"`
	TombstonesOnDelete types.Bool                      `tfsdk:"tombstones_on_delete"`
	TxMetadataTopic    types.String                    `tfsdk:"tx_metadata_topic"`
}

type KafkaDataTypeConfigModel struct {
	BinaryHandlingMode  types.String `tfsdk:"binary_handling_mode"`
	DecimalHandlingMode types.String `tfsdk:"decimal_handling_mode"`
	TimePrecisionMode   types.String `tfsdk:"time_precision_mode"`
}

type KaformatConfigModel struct {
	KeySerde   *KafkaSerDeModel `tfsdk:"key_serde"`
	ValueSerde *KafkaSerDeModel `tfsdk:"value_serde"`
}

type KafkaSerDeModel struct {
	JSON     *KafkaJsonModel     `tfsdk:"json"`
	Avro     *KafkaAvroModel     `tfsdk:"avro"`
	Protobuf *KafkaProtobufModel `tfsdk:"protobuf"`
}

type KafkaJsonModel struct {
	Options        *KafkaJsonOptionsModel    `tfsdk:"options"`
	SchemaRegistry *KafkaSchemaRegistryModel `tfsdk:"schema_registry"`
}

type KafkaJsonOptionsModel struct {
	EmbedSchemaInMessage types.Bool `tfsdk:"embed_schema_in_message"`
}

type KafkaSchemaRegistryModel struct {
	Confluent *KafkaConfluentModel `tfsdk:"confluent"`
	Apicurio  *KafkaApicurioModel  `tfsdk:"apicurio"`
}

type KafkaConfluentModel struct {
	Password types.String `tfsdk:"password"`
	URL      types.String `tfsdk:"url"`
	Username types.String `tfsdk:"username"`
}

type KafkaApicurioModel struct {
	Password types.String `tfsdk:"password"`
	URL      types.String `tfsdk:"url"`
	Username types.String `tfsdk:"username"`
}

type KafkaAvroModel struct {
	SchemaRegistry *KafkaSchemaRegistryModel `tfsdk:"schema_registry"`
}

type KafkaProtobufModel struct {
	SchemaRegistry *KafkaSchemaRegistryModel `tfsdk:"schema_registry"`
}

type KafkaDebeziumHeaderConfigModel struct {
	Context        types.Bool   `tfsdk:"context"`
	Db             types.Bool   `tfsdk:"db"`
	DbName         types.String `tfsdk:"db_name"`
	Op             types.Bool   `tfsdk:"op"`
	OpName         types.String `tfsdk:"op_name"`
	PkUpdate       types.Bool   `tfsdk:"pk_update"`
	Prefix         types.String `tfsdk:"prefix"`
	Schema         types.Bool   `tfsdk:"schema"`
	SchemaName     types.String `tfsdk:"schema_name"`
	SourceName     types.String `tfsdk:"source_name"`
	SourceTemplate types.String `tfsdk:"source_template"`
	Tbl            types.Bool   `tfsdk:"tbl"`
	TblName        types.String `tfsdk:"tbl_name"`
}

type KafkaSupermetalFormatModel struct {
	FormatConfig       *KaformatConfigModel `tfsdk:"format_config"`
	TombstonesOnDelete types.Bool           `tfsdk:"tombstones_on_delete"`
}

type KafkaTopicOptionsModel struct {
	Config             []*KafkaPropertyModel `tfsdk:"config"`
	NamingMode         types.String          `tfsdk:"naming_mode"`
	OperationTimeoutMs types.Int32           `tfsdk:"operation_timeout_ms"`
	Partitions         types.Int32           `tfsdk:"partitions"`
	ReplicationFactor  types.Int32           `tfsdk:"replication_factor"`
}

// =============================================================================
// MongoSource Models
// =============================================================================

type MongoSourceModel struct {
	Catalog              *CatalogModel                `tfsdk:"catalog"`
	Address              types.String                 `tfsdk:"address"`
	AuthenticationSource types.String                 `tfsdk:"authentication_source"`
	Database             types.String                 `tfsdk:"database"`
	MaxPoolSize          types.Int32                  `tfsdk:"max_pool_size"`
	Password             types.String                 `tfsdk:"password"`
	SslMode              *MongoSslModeModel           `tfsdk:"ssl_mode"`
	User                 types.String                 `tfsdk:"user"`
	FlattenBody          types.Bool                   `tfsdk:"flatten_body"`
	FlattenMaxDepth      types.Int32                  `tfsdk:"flatten_max_depth"`
	ReplicationType      *MongoReplicationTypeModel   `tfsdk:"replication_type"`
	SystemColumns        *MigrationSystemColumnsModel `tfsdk:"system_columns"`
}

type MongoSslModeModel struct {
	Disable *MongoDisableModel `tfsdk:"disable"`
	Enable  *MongoEnableModel  `tfsdk:"enable"`
}

type MongoDisableModel struct {
}

type MongoEnableModel struct {
	CAFile      types.String `tfsdk:"ca_file"`
	CertKeyFile types.String `tfsdk:"cert_key_file"`
}

type MongoReplicationTypeModel struct {
	ChangeStreams *MongoChangeStreamsModel `tfsdk:"change_streams"`
	Snapshot      *MongoSnapshotModel      `tfsdk:"snapshot"`
}

type MongoChangeStreamsModel struct {
	ReplicationMode *MongoReplicationModeModel `tfsdk:"replication_mode"`
	SkipSnapshot    types.Bool                 `tfsdk:"skip_snapshot"`
}

type MongoReplicationModeModel struct {
	SchemaMode     *MongoSchemaModeModel     `tfsdk:"schema_mode"`
	SchemalessMode *MongoSchemalessModeModel `tfsdk:"schemaless_mode"`
}

type MongoSchemaModeModel struct {
	InferTypedStrings     types.Bool              `tfsdk:"infer_typed_strings"`
	MajorityTypeThreshold types.Float64           `tfsdk:"majority_type_threshold"`
	ObjectStore           *BufferObjectStoreModel `tfsdk:"object_store"`
}

type MongoSchemalessModeModel struct {
}

type MongoSnapshotModel struct {
	ReplicationMode *MongoReplicationModeModel `tfsdk:"replication_mode"`
}

// =============================================================================
// MySqlSource Models
// =============================================================================

type MySqlSourceModel struct {
	Catalog                  *CatalogModel                       `tfsdk:"catalog"`
	Database                 types.String                        `tfsdk:"database"`
	Host                     types.String                        `tfsdk:"host"`
	MaxPoolSize              types.Int32                         `tfsdk:"max_pool_size"`
	Password                 types.String                        `tfsdk:"password"`
	Port                     types.Int32                         `tfsdk:"port"`
	SslMode                  *MysqlSslModeModel                  `tfsdk:"ssl_mode"`
	Tunnel                   *SshTunnelTypeModel                 `tfsdk:"tunnel"`
	User                     types.String                        `tfsdk:"user"`
	InferTinyint1AsBoolean   types.Bool                          `tfsdk:"infer_tinyint1_as_boolean"`
	KeylessTableStrategy     *MigrationKeylessTableStrategyModel `tfsdk:"keyless_table_strategy"`
	ParallelSnapshotsEnabled types.Bool                          `tfsdk:"parallel_snapshots_enabled"`
	SkipSnapshot             types.Bool                          `tfsdk:"skip_snapshot"`
	SystemColumns            *MigrationSystemColumnsModel        `tfsdk:"system_columns"`
}

type MysqlSslModeModel struct {
	Disable        *MysqlDisableModel        `tfsdk:"disable"`
	Require        *MysqlRequireModel        `tfsdk:"require"`
	VerifyCA       *MysqlVerifyCaModel       `tfsdk:"verify_ca"`
	VerifyIdentity *MysqlVerifyIdentityModel `tfsdk:"verify_identity"`
}

type MysqlDisableModel struct {
}

type MysqlRequireModel struct {
}

type MysqlVerifyCaModel struct {
	CAFile types.String `tfsdk:"ca_file"`
}

type MysqlVerifyIdentityModel struct {
	CAFile types.String `tfsdk:"ca_file"`
}

// =============================================================================
// OracleSource Models
// =============================================================================

type OracleSourceModel struct {
	Catalog                  *CatalogModel                       `tfsdk:"catalog"`
	ConnectString            types.String                        `tfsdk:"connect_string"`
	MaxPoolSize              types.Int32                         `tfsdk:"max_pool_size"`
	Password                 types.String                        `tfsdk:"password"`
	Pdb                      types.String                        `tfsdk:"pdb"`
	User                     types.String                        `tfsdk:"user"`
	KeylessTableStrategy     *MigrationKeylessTableStrategyModel `tfsdk:"keyless_table_strategy"`
	ParallelSnapshotsEnabled types.Bool                          `tfsdk:"parallel_snapshots_enabled"`
	ReplicationType          *OracleReplicationTypeModel         `tfsdk:"replication_type"`
	SystemColumns            *MigrationSystemColumnsModel        `tfsdk:"system_columns"`
}

type OracleReplicationTypeModel struct {
	LogMiner *OracleLogMinerModel `tfsdk:"log_miner"`
}

type OracleLogMinerModel struct {
	CommittedDataOnly        types.Bool   `tfsdk:"committed_data_only"`
	Dict                     types.String `tfsdk:"dict"`
	MaxBufferMemorySizePerTx types.Int64  `tfsdk:"max_buffer_memory_size_per_tx"`
	PollIntervalSecs         types.Int64  `tfsdk:"poll_interval_secs"`
}

// =============================================================================
// PostgresSource Models
// =============================================================================

type PostgresSourceModel struct {
	Catalog                     *CatalogModel                       `tfsdk:"catalog"`
	Database                    types.String                        `tfsdk:"database"`
	Host                        types.String                        `tfsdk:"host"`
	MaxPoolSize                 types.Int64                         `tfsdk:"max_pool_size"`
	OperationLockTimeoutSeconds types.Int32                         `tfsdk:"operation_lock_timeout_seconds"`
	Password                    types.String                        `tfsdk:"password"`
	Port                        types.Int32                         `tfsdk:"port"`
	SslCert                     types.String                        `tfsdk:"ssl_cert"`
	SslKey                      types.String                        `tfsdk:"ssl_key"`
	SslMode                     types.String                        `tfsdk:"ssl_mode"`
	SslRootCert                 types.String                        `tfsdk:"ssl_root_cert"`
	Tunnel                      *SshTunnelTypeModel                 `tfsdk:"tunnel"`
	User                        types.String                        `tfsdk:"user"`
	KeylessTableStrategy        *MigrationKeylessTableStrategyModel `tfsdk:"keyless_table_strategy"`
	ParallelSnapshotsEnabled    types.Bool                          `tfsdk:"parallel_snapshots_enabled"`
	PartitionsAsRoot            types.Bool                          `tfsdk:"partitions_as_root"`
	ReplicationType             *PostgresReplicationTypeModel       `tfsdk:"replication_type"`
	SystemColumns               *MigrationSystemColumnsModel        `tfsdk:"system_columns"`
}

type PostgresReplicationTypeModel struct {
	LogicalReplication *PostgresLogicalReplicationModel `tfsdk:"logical_replication"`
	Snapshot           *PostgresSnapshotModel           `tfsdk:"snapshot"`
	QueryBased         *PostgresQueryBasedModel         `tfsdk:"query_based"`
}

type PostgresLogicalReplicationModel struct {
	PublicationName    types.String `tfsdk:"publication_name"`
	RetryWindowSeconds types.Int64  `tfsdk:"retry_window_seconds"`
	SkipSnapshots      types.Bool   `tfsdk:"skip_snapshots"`
}

type PostgresSnapshotModel struct {
}

type PostgresQueryBasedModel struct {
	DeleteTracking      *PostgresDeleteTrackingModel `tfsdk:"delete_tracking"`
	MaxSkipCycles       types.Int32                  `tfsdk:"max_skip_cycles"`
	PollIntervalSeconds types.Int32                  `tfsdk:"poll_interval_seconds"`
}

type PostgresDeleteTrackingModel struct {
	Enabled *PostgresDeleteTrackingConfigModel `tfsdk:"enabled"`
}

type PostgresDeleteTrackingConfigModel struct {
	PkIndexStore        *BufferObjectStoreModel `tfsdk:"pk_index_store"`
	PollIntervalSeconds types.Int32             `tfsdk:"poll_interval_seconds"`
}

// =============================================================================
// PostgresSink Models
// =============================================================================

type PostgresSinkModel struct {
	Database                    types.String            `tfsdk:"database"`
	Host                        types.String            `tfsdk:"host"`
	MaxPoolSize                 types.Int64             `tfsdk:"max_pool_size"`
	OperationLockTimeoutSeconds types.Int32             `tfsdk:"operation_lock_timeout_seconds"`
	Password                    types.String            `tfsdk:"password"`
	Port                        types.Int32             `tfsdk:"port"`
	SslCert                     types.String            `tfsdk:"ssl_cert"`
	SslKey                      types.String            `tfsdk:"ssl_key"`
	SslMode                     types.String            `tfsdk:"ssl_mode"`
	SslRootCert                 types.String            `tfsdk:"ssl_root_cert"`
	Tunnel                      *SshTunnelTypeModel     `tfsdk:"tunnel"`
	User                        types.String            `tfsdk:"user"`
	MigrationStrategy           *MigrationStrategyModel `tfsdk:"migration_strategy"`
	TargetSchema                types.String            `tfsdk:"target_schema"`
}

// =============================================================================
// SnowflakeSink Models
// =============================================================================

type SnowflakeSinkModel struct {
	AccountIdentifier types.String               `tfsdk:"account_identifier"`
	Auth              *SnowflakeAuthModel        `tfsdk:"auth"`
	Role              types.String               `tfsdk:"role"`
	User              types.String               `tfsdk:"user"`
	Warehouse         types.String               `tfsdk:"warehouse"`
	HistoryMode       *MigrationHistoryModeModel `tfsdk:"history_mode"`
	MigrationStrategy *MigrationStrategyModel    `tfsdk:"migration_strategy"`
	TargetDatabase    types.String               `tfsdk:"target_database"`
	TargetSchema      types.String               `tfsdk:"target_schema"`
	UseTransactions   types.Bool                 `tfsdk:"use_transactions"`
}

type SnowflakeAuthModel struct {
	Password *SnowflakePasswordModel `tfsdk:"password"`
	KeyPair  *SnowflakeKeyPairModel  `tfsdk:"key_pair"`
}

type SnowflakePasswordModel struct {
	Password types.String `tfsdk:"password"`
}

type SnowflakeKeyPairModel struct {
	PrivateKeyPassword types.String `tfsdk:"private_key_password"`
	PrivateKeyPEM      types.String `tfsdk:"private_key_pem"`
}

// =============================================================================
// SqlServerSource Models
// =============================================================================

type SqlServerSourceModel struct {
	Catalog                  *CatalogModel                       `tfsdk:"catalog"`
	Auth                     *SqlServerAuthModel                 `tfsdk:"auth"`
	Database                 types.String                        `tfsdk:"database"`
	Host                     types.String                        `tfsdk:"host"`
	MaxPoolSize              types.Int32                         `tfsdk:"max_pool_size"`
	Port                     types.Int32                         `tfsdk:"port"`
	SslMode                  *SqlServerSslModeModel              `tfsdk:"ssl_mode"`
	KeylessTableStrategy     *MigrationKeylessTableStrategyModel `tfsdk:"keyless_table_strategy"`
	ParallelSnapshotsEnabled types.Bool                          `tfsdk:"parallel_snapshots_enabled"`
	ReplicationType          *SqlServerReplicationTypeModel      `tfsdk:"replication_type"`
	SnapshotIsolation        types.String                        `tfsdk:"snapshot_isolation"`
	SystemColumns            *MigrationSystemColumnsModel        `tfsdk:"system_columns"`
}

type SqlServerAuthModel struct {
	Standard        *SqlServerStandardAuthModel `tfsdk:"standard"`
	Windows         *SqlServerWindowsAuthModel  `tfsdk:"windows"`
	Activedirectory *SqlServerAdAuthModel       `tfsdk:"activedirectory"`
}

type SqlServerStandardAuthModel struct {
	Password types.String `tfsdk:"password"`
	User     types.String `tfsdk:"user"`
}

type SqlServerWindowsAuthModel struct {
	Password types.String `tfsdk:"password"`
	User     types.String `tfsdk:"user"`
}

type SqlServerAdAuthModel struct {
	Token types.String `tfsdk:"token"`
}

type SqlServerSslModeModel struct {
	Disable *SqlServerDisableModel `tfsdk:"disable"`
	Enable  *SqlServerEnableModel  `tfsdk:"enable"`
}

type SqlServerDisableModel struct {
}

type SqlServerEnableModel struct {
	CAFile types.String `tfsdk:"ca_file"`
}

type SqlServerReplicationTypeModel struct {
	CaptureTableReplication *SqlServerCaptureTableReplicationModel `tfsdk:"capture_table_replication"`
	Snapshot                *SqlServerSnapshotModel                `tfsdk:"snapshot"`
}

type SqlServerCaptureTableReplicationModel struct {
	CdcMaxScans             types.Int32 `tfsdk:"cdc_max_scans"`
	CdcMaxTrans             types.Int32 `tfsdk:"cdc_max_trans"`
	CdcPollIntervalSecs     types.Int64 `tfsdk:"cdc_poll_interval_secs"`
	SkipSnapshot            types.Bool  `tfsdk:"skip_snapshot"`
	SkipTablesWithoutCt     types.Bool  `tfsdk:"skip_tables_without_ct"`
	TransactionalCdcEnabled types.Bool  `tfsdk:"transactional_cdc_enabled"`
}

type SqlServerSnapshotModel struct {
}

// =============================================================================
// WebhookSink Models
// =============================================================================

type WebhookSinkModel struct {
	Auth             *WebhookAuthModel            `tfsdk:"auth"`
	Batch            *WebhookBatchConfigModel     `tfsdk:"batch"`
	Compression      types.String                 `tfsdk:"compression"`
	Format           *KaformatModel               `tfsdk:"format"`
	Headers          *WebhookHeadersConfigModel   `tfsdk:"headers"`
	PathTemplate     types.String                 `tfsdk:"path_template"`
	RateLimit        *WebhookRateLimitConfigModel `tfsdk:"rate_limit"`
	RequestTimeoutMs types.Int32                  `tfsdk:"request_timeout_ms"`
	Retry            *WebhookRetryConfigModel     `tfsdk:"retry"`
	URL              types.String                 `tfsdk:"url"`
}

type WebhookAuthModel struct {
	Bearer *WebhookBearerAuthModel `tfsdk:"bearer"`
	Basic  *WebhookBasicAuthModel  `tfsdk:"basic"`
	Header *WebhookHeaderAuthModel `tfsdk:"header"`
}

type WebhookBearerAuthModel struct {
	Token types.String `tfsdk:"token"`
}

type WebhookBasicAuthModel struct {
	Password types.String `tfsdk:"password"`
	Username types.String `tfsdk:"username"`
}

type WebhookHeaderAuthModel struct {
	Name  types.String `tfsdk:"name"`
	Value types.String `tfsdk:"value"`
}

type WebhookBatchConfigModel struct {
	MaxBatchSize    types.Int32 `tfsdk:"max_batch_size"`
	MaxPayloadBytes types.Int64 `tfsdk:"max_payload_bytes"`
}

type WebhookHeadersConfigModel struct {
	IdempotencyKey       types.Bool                         `tfsdk:"idempotency_key"`
	IdempotencyKeyHeader types.String                       `tfsdk:"idempotency_key_header"`
	SourceSchema         types.Bool                         `tfsdk:"source_schema"`
	SourceSchemaHeader   types.String                       `tfsdk:"source_schema_header"`
	SourceTable          types.Bool                         `tfsdk:"source_table"`
	SourceTableHeader    types.String                       `tfsdk:"source_table_header"`
	Static               map[string]*WebhookHttpHeaderModel `tfsdk:"static_"`
}

type WebhookHttpHeaderModel struct {
	Value types.String `tfsdk:"value"`
}

type WebhookRateLimitConfigModel struct {
	MaxBytesPerSecond    types.Int64 `tfsdk:"max_bytes_per_second"`
	MaxRequestsPerSecond types.Int32 `tfsdk:"max_requests_per_second"`
}

type WebhookRetryConfigModel struct {
	InitialBackoffMs   types.Int32 `tfsdk:"initial_backoff_ms"`
	MaxBackoffMs       types.Int32 `tfsdk:"max_backoff_ms"`
	MaxRetries         types.Int32 `tfsdk:"max_retries"`
	MaxRetryDurationMs types.Int64 `tfsdk:"max_retry_duration_ms"`
}
