// Code generated by supermetal-inc/terraform-provider-gen@6a2b361, spec v0.1.10. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/supermetal-inc/terraform-provider-supermetal/internal/api"
)

type ConnectorModel struct {
	ID       types.String `tfsdk:"id"`
	Name     types.String `tfsdk:"name"`
	Disabled types.Bool   `tfsdk:"disabled"`
	Source   *SourceModel `tfsdk:"source"`
	Sink     *SinkModel   `tfsdk:"sink"`
}

type SourceModel struct {
	Db2        *Db2SourceModel       `tfsdk:"db2"`
	FileSource *FileSourceModel      `tfsdk:"file_source"`
	Mongo      *MongoSourceModel     `tfsdk:"mongo"`
	Mysql      *MySqlSourceModel     `tfsdk:"mysql"`
	Oracle     *OracleSourceModel    `tfsdk:"oracle"`
	Postgres   *PostgresSourceModel  `tfsdk:"postgres"`
	Sqlserver  *SqlServerSourceModel `tfsdk:"sqlserver"`
}

type SinkModel struct {
	BigQuery   *BigQuerySinkModel   `tfsdk:"big_query"`
	Clickhouse *ClickhouseSinkModel `tfsdk:"clickhouse"`
	Databricks *DatabricksSinkModel `tfsdk:"databricks"`
	Doris      *DorisSinkModel      `tfsdk:"doris"`
	Duckdb     *DuckDBSinkModel     `tfsdk:"duckdb"`
	Iceberg    *IcebergSinkModel    `tfsdk:"iceberg"`
	Kafka      *KafkaSinkModel      `tfsdk:"kafka"`
	Motherduck *DuckDBSinkModel     `tfsdk:"motherduck"`
	Postgres   *PostgresSinkModel   `tfsdk:"postgres"`
	Snowflake  *SnowflakeSinkModel  `tfsdk:"snowflake"`
	Webhook    *WebhookSinkModel    `tfsdk:"webhook"`
}

func sourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"db2": schema.SingleNestedAttribute{
			MarkdownDescription: "Db2 replication source",
			Optional:            true,
			Attributes:          db2SourceAttributes(),
		},
		"file_source": schema.SingleNestedAttribute{
			MarkdownDescription: "Ingest files from object stores (S3, GCS, Azure Blob) or filesystems (local, SFTP)",
			Optional:            true,
			Attributes:          fileSourceAttributes(),
		},
		"mongo": schema.SingleNestedAttribute{
			MarkdownDescription: "MongoDB replication source",
			Optional:            true,
			Attributes:          mongoSourceAttributes(),
		},
		"mysql": schema.SingleNestedAttribute{
			MarkdownDescription: "MySQL replication source",
			Optional:            true,
			Attributes:          mysqlSourceAttributes(),
		},
		"oracle": schema.SingleNestedAttribute{
			MarkdownDescription: "Oracle replication source",
			Optional:            true,
			Attributes:          oracleSourceAttributes(),
		},
		"postgres": schema.SingleNestedAttribute{
			MarkdownDescription: "PostgreSQL replication source",
			Optional:            true,
			Attributes:          postgresSourceAttributes(),
		},
		"sqlserver": schema.SingleNestedAttribute{
			MarkdownDescription: "SQL Server replication source",
			Optional:            true,
			Attributes:          sqlserverSourceAttributes(),
		},
	}
}

func sinkAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"big_query": schema.SingleNestedAttribute{
			MarkdownDescription: "BigQuery destination",
			Optional:            true,
			Attributes:          bigquerySinkAttributes(),
		},
		"clickhouse": schema.SingleNestedAttribute{
			MarkdownDescription: "Configuration for a ClickHouse data sink",
			Optional:            true,
			Attributes:          clickhouseSinkAttributes(),
		},
		"databricks": schema.SingleNestedAttribute{
			MarkdownDescription: "Databricks destination",
			Optional:            true,
			Attributes:          databricksSinkAttributes(),
		},
		"doris": schema.SingleNestedAttribute{
			MarkdownDescription: "Apache Doris sink configuration",
			Optional:            true,
			Attributes:          dorisSinkAttributes(),
		},
		"duckdb": schema.SingleNestedAttribute{
			MarkdownDescription: "DuckDB sink",
			Optional:            true,
			Attributes:          duckdbSinkAttributes(),
		},
		"iceberg": schema.SingleNestedAttribute{
			MarkdownDescription: "Iceberg destination",
			Optional:            true,
			Attributes:          icebergSinkAttributes(),
		},
		"kafka": schema.SingleNestedAttribute{
			MarkdownDescription: "Kafka destination",
			Optional:            true,
			Attributes:          kafkaSinkAttributes(),
		},
		"motherduck": schema.SingleNestedAttribute{
			MarkdownDescription: "DuckDB sink",
			Optional:            true,
			Attributes:          duckdbSinkAttributes(),
		},
		"postgres": schema.SingleNestedAttribute{
			MarkdownDescription: "PostgreSQL destination",
			Optional:            true,
			Attributes:          postgresSinkAttributes(),
		},
		"snowflake": schema.SingleNestedAttribute{
			MarkdownDescription: "Snowflake destination",
			Optional:            true,
			Attributes:          snowflakeSinkAttributes(),
		},
		"webhook": schema.SingleNestedAttribute{
			MarkdownDescription: "Webhook destination",
			Optional:            true,
			Attributes:          webhookSinkAttributes(),
		},
	}
}

func (m *SourceModel) toAPI() (api.ConnectorSource, diag.Diagnostics) {
	var source api.ConnectorSource
	var diags diag.Diagnostics

	if m.Db2 != nil {
		inner, d := m.Db2.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource6{Db2: inner}
		if err := source.FromConnectorSource6(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.FileSource != nil {
		inner, d := m.FileSource.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource5{FileSource: inner}
		if err := source.FromConnectorSource5(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.Mongo != nil {
		inner, d := m.Mongo.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource3{Mongo: inner}
		if err := source.FromConnectorSource3(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.Mysql != nil {
		inner, d := m.Mysql.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource2{Mysql: inner}
		if err := source.FromConnectorSource2(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.Oracle != nil {
		inner, d := m.Oracle.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource4{Oracle: inner}
		if err := source.FromConnectorSource4(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.Postgres != nil {
		inner, d := m.Postgres.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource0{Postgres: inner}
		if err := source.FromConnectorSource0(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.Sqlserver != nil {
		inner, d := m.Sqlserver.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource1{Sqlserver: inner}
		if err := source.FromConnectorSource1(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	}
	return source, diags
}

func (m *SinkModel) toAPI() (api.ConnectorSink, diag.Diagnostics) {
	var sink api.ConnectorSink
	var diags diag.Diagnostics

	if m.BigQuery != nil {
		inner, d := m.BigQuery.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink11{BigQuery: inner}
		if err := sink.FromConnectorSink11(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Clickhouse != nil {
		inner, d := m.Clickhouse.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink1{Clickhouse: inner}
		if err := sink.FromConnectorSink1(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Databricks != nil {
		inner, d := m.Databricks.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink5{Databricks: inner}
		if err := sink.FromConnectorSink5(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Doris != nil {
		inner, d := m.Doris.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink8{Doris: inner}
		if err := sink.FromConnectorSink8(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Duckdb != nil {
		inner, d := m.Duckdb.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink9{Duckdb: inner}
		if err := sink.FromConnectorSink9(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Iceberg != nil {
		inner, d := m.Iceberg.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink7{Iceberg: inner}
		if err := sink.FromConnectorSink7(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Kafka != nil {
		inner, d := m.Kafka.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink4{Kafka: inner}
		if err := sink.FromConnectorSink4(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Motherduck != nil {
		inner, d := m.Motherduck.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink10{Motherduck: inner}
		if err := sink.FromConnectorSink10(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Postgres != nil {
		inner, d := m.Postgres.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink0{Postgres: inner}
		if err := sink.FromConnectorSink0(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Snowflake != nil {
		inner, d := m.Snowflake.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink2{Snowflake: inner}
		if err := sink.FromConnectorSink2(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Webhook != nil {
		inner, d := m.Webhook.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink6{Webhook: inner}
		if err := sink.FromConnectorSink6(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	}
	return sink, diags
}

func (m *SourceModel) mergeFromAPI(source api.ConnectorSource, state *SourceModel) {
	if v, err := source.AsConnectorSource6(); err == nil && v.Db2.Connection.Host != "" {
		if m.Db2 == nil {
			m.Db2 = &Db2SourceModel{}
		}
		var st *Db2SourceModel
		if state != nil {
			st = state.Db2
		}
		m.Db2.mergeFromAPI(v.Db2, st)
	}
	if v, err := source.AsConnectorSource5(); err == nil && v.FileSource.ObjectStore.Url != "" {
		if m.FileSource == nil {
			m.FileSource = &FileSourceModel{}
		}
		var st *FileSourceModel
		if state != nil {
			st = state.FileSource
		}
		m.FileSource.mergeFromAPI(v.FileSource, st)
	}
	if v, err := source.AsConnectorSource3(); err == nil && v.Mongo.Connection.Address != "" {
		if m.Mongo == nil {
			m.Mongo = &MongoSourceModel{}
		}
		var st *MongoSourceModel
		if state != nil {
			st = state.Mongo
		}
		m.Mongo.mergeFromAPI(v.Mongo, st)
	}
	if v, err := source.AsConnectorSource2(); err == nil && v.Mysql.Connection.Host != "" {
		if m.Mysql == nil {
			m.Mysql = &MySqlSourceModel{}
		}
		var st *MySqlSourceModel
		if state != nil {
			st = state.Mysql
		}
		m.Mysql.mergeFromAPI(v.Mysql, st)
	}
	if v, err := source.AsConnectorSource4(); err == nil && v.Oracle.Connection.ConnectString != "" {
		if m.Oracle == nil {
			m.Oracle = &OracleSourceModel{}
		}
		var st *OracleSourceModel
		if state != nil {
			st = state.Oracle
		}
		m.Oracle.mergeFromAPI(v.Oracle, st)
	}
	if v, err := source.AsConnectorSource0(); err == nil && v.Postgres.Connection.Host != "" {
		if m.Postgres == nil {
			m.Postgres = &PostgresSourceModel{}
		}
		var st *PostgresSourceModel
		if state != nil {
			st = state.Postgres
		}
		m.Postgres.mergeFromAPI(v.Postgres, st)
	}
	if v, err := source.AsConnectorSource1(); err == nil && v.Sqlserver.Connection.Host != "" {
		if m.Sqlserver == nil {
			m.Sqlserver = &SqlServerSourceModel{}
		}
		var st *SqlServerSourceModel
		if state != nil {
			st = state.Sqlserver
		}
		m.Sqlserver.mergeFromAPI(v.Sqlserver, st)
	}
}

func (m *SinkModel) mergeFromAPI(sink api.ConnectorSink, state *SinkModel) {
	if v, err := sink.AsConnectorSink11(); err == nil && v.BigQuery.ProjectId != "" {
		if m.BigQuery == nil {
			m.BigQuery = &BigQuerySinkModel{}
		}
		var st *BigQuerySinkModel
		if state != nil {
			st = state.BigQuery
		}
		m.BigQuery.mergeFromAPI(v.BigQuery, st)
	}
	if v, err := sink.AsConnectorSink1(); err == nil && v.Clickhouse.Connection.HttpUrl != "" {
		if m.Clickhouse == nil {
			m.Clickhouse = &ClickhouseSinkModel{}
		}
		var st *ClickhouseSinkModel
		if state != nil {
			st = state.Clickhouse
		}
		m.Clickhouse.mergeFromAPI(v.Clickhouse, st)
	}
	if v, err := sink.AsConnectorSink5(); err == nil && v.Databricks.TargetCatalog != "" {
		if m.Databricks == nil {
			m.Databricks = &DatabricksSinkModel{}
		}
		var st *DatabricksSinkModel
		if state != nil {
			st = state.Databricks
		}
		m.Databricks.mergeFromAPI(v.Databricks, st)
	}
	if v, err := sink.AsConnectorSink8(); err == nil && v.Doris.Connection.FeHttpUrl != "" {
		if m.Doris == nil {
			m.Doris = &DorisSinkModel{}
		}
		var st *DorisSinkModel
		if state != nil {
			st = state.Doris
		}
		m.Doris.mergeFromAPI(v.Doris, st)
	}
	if v, err := sink.AsConnectorSink9(); err == nil && v.Duckdb.TargetDatabase != "" {
		if m.Duckdb == nil {
			m.Duckdb = &DuckDBSinkModel{}
		}
		var st *DuckDBSinkModel
		if state != nil {
			st = state.Duckdb
		}
		m.Duckdb.mergeFromAPI(v.Duckdb, st)
	}
	if v, err := sink.AsConnectorSink7(); err == nil && len(v.Iceberg.TargetNamespace) > 0 {
		if m.Iceberg == nil {
			m.Iceberg = &IcebergSinkModel{}
		}
		var st *IcebergSinkModel
		if state != nil {
			st = state.Iceberg
		}
		m.Iceberg.mergeFromAPI(v.Iceberg, st)
	}
	if v, err := sink.AsConnectorSink4(); err == nil && len(v.Kafka.Connection.Brokers) > 0 {
		if m.Kafka == nil {
			m.Kafka = &KafkaSinkModel{}
		}
		var st *KafkaSinkModel
		if state != nil {
			st = state.Kafka
		}
		m.Kafka.mergeFromAPI(v.Kafka, st)
	}
	if v, err := sink.AsConnectorSink10(); err == nil && v.Motherduck.TargetDatabase != "" {
		if m.Motherduck == nil {
			m.Motherduck = &DuckDBSinkModel{}
		}
		var st *DuckDBSinkModel
		if state != nil {
			st = state.Motherduck
		}
		m.Motherduck.mergeFromAPI(v.Motherduck, st)
	}
	if v, err := sink.AsConnectorSink0(); err == nil && v.Postgres.Connection.Host != "" {
		if m.Postgres == nil {
			m.Postgres = &PostgresSinkModel{}
		}
		var st *PostgresSinkModel
		if state != nil {
			st = state.Postgres
		}
		m.Postgres.mergeFromAPI(v.Postgres, st)
	}
	if v, err := sink.AsConnectorSink2(); err == nil && v.Snowflake.Connection.AccountIdentifier != "" {
		if m.Snowflake == nil {
			m.Snowflake = &SnowflakeSinkModel{}
		}
		var st *SnowflakeSinkModel
		if state != nil {
			st = state.Snowflake
		}
		m.Snowflake.mergeFromAPI(v.Snowflake, st)
	}
	if v, err := sink.AsConnectorSink6(); err == nil && v.Webhook.Url != "" {
		if m.Webhook == nil {
			m.Webhook = &WebhookSinkModel{}
		}
		var st *WebhookSinkModel
		if state != nil {
			st = state.Webhook
		}
		m.Webhook.mergeFromAPI(v.Webhook, st)
	}
}

func (m *ConnectorModel) toAPIConnector() (api.ConnectorConnector, diag.Diagnostics) {
	var diags diag.Diagnostics

	connector := api.ConnectorConnector{
		Id:       m.ID.ValueString(),
		Name:     m.Name.ValueStringPointer(),
		Disabled: m.Disabled.ValueBoolPointer(),
	}

	if m.Source != nil {
		source, d := m.Source.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return connector, diags
		}
		connector.Source = source
	}

	if m.Sink != nil {
		sink, d := m.Sink.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return connector, diags
		}
		connector.Sink = sink
	}

	return connector, diags
}

func (m *ConnectorModel) mergeFromAPI(connector api.ConnectorConnector, state *ConnectorModel) {
	m.ID = types.StringValue(connector.Id)

	if connector.Name != nil {
		m.Name = types.StringValue(*connector.Name)
	}

	if connector.Disabled != nil {
		m.Disabled = types.BoolValue(*connector.Disabled)
	}

	if m.Source == nil {
		m.Source = &SourceModel{}
	}
	var stateSource *SourceModel
	if state != nil {
		stateSource = state.Source
	}
	m.Source.mergeFromAPI(connector.Source, stateSource)

	if m.Sink == nil {
		m.Sink = &SinkModel{}
	}
	var stateSink *SinkModel
	if state != nil {
		stateSink = state.Sink
	}
	m.Sink.mergeFromAPI(connector.Sink, stateSink)
}

func countSourceVariants(m *SourceModel) int {
	if m == nil {
		return 0
	}
	count := 0
	if m.Db2 != nil {
		count++
	}
	if m.FileSource != nil {
		count++
	}
	if m.Mongo != nil {
		count++
	}
	if m.Mysql != nil {
		count++
	}
	if m.Oracle != nil {
		count++
	}
	if m.Postgres != nil {
		count++
	}
	if m.Sqlserver != nil {
		count++
	}
	return count
}

func countSinkVariants(m *SinkModel) int {
	if m == nil {
		return 0
	}
	count := 0
	if m.BigQuery != nil {
		count++
	}
	if m.Clickhouse != nil {
		count++
	}
	if m.Databricks != nil {
		count++
	}
	if m.Doris != nil {
		count++
	}
	if m.Duckdb != nil {
		count++
	}
	if m.Iceberg != nil {
		count++
	}
	if m.Kafka != nil {
		count++
	}
	if m.Motherduck != nil {
		count++
	}
	if m.Postgres != nil {
		count++
	}
	if m.Snowflake != nil {
		count++
	}
	if m.Webhook != nil {
		count++
	}
	return count
}
