// Code generated by supermetal-inc/terraform-provider-gen@eeb2b71, spec v0.1.13. DO NOT EDIT.

package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/supermetal-inc/terraform-provider-supermetal/internal/api"
)

var declaredSecretJSONPaths = [][]string{
	{"buffer", "object_store", "root_certificate_pem"},
	{"sink", "big_query", "auth", "service_account_key", "key_json"},
	{"sink", "clickhouse", "connection", "password"},
	{"sink", "clickhouse", "connection", "ssl_client_cert_pem"},
	{"sink", "clickhouse", "connection", "ssl_client_key_pem"},
	{"sink", "clickhouse", "connection", "ssl_root_cert"},
	{"sink", "databricks", "auth", "m2m", "client_secret"},
	{"sink", "databricks", "auth", "pat", "personal_access_token"},
	{"sink", "doris", "connection", "password"},
	{"sink", "doris", "connection", "ssl_client_cert_pem"},
	{"sink", "doris", "connection", "ssl_client_key_pem"},
	{"sink", "doris", "connection", "ssl_root_cert"},
	{"sink", "duckdb", "connection", "pg", "password"},
	{"sink", "duckdb", "connection", "pg", "ssl_cert"},
	{"sink", "duckdb", "connection", "pg", "ssl_key"},
	{"sink", "duckdb", "connection", "pg", "ssl_root_cert"},
	{"sink", "duckdb", "connection", "pg", "tunnel", "ssh", "auth", "bring_your_own_key", "private_key"},
	{"sink", "duckdb", "connection", "pg", "tunnel", "ssh", "auth", "generated_key", "private_key"},
	{"sink", "duckdb", "connection", "quack", "token"},
	{"sink", "file_sink", "object_store", "root_certificate_pem"},
	{"sink", "iceberg", "catalog", "glue", "access_key_id"},
	{"sink", "iceberg", "catalog", "glue", "secret_access_key"},
	{"sink", "iceberg", "catalog", "glue", "session_token"},
	{"sink", "iceberg", "catalog", "rest", "auth", "basic", "password"},
	{"sink", "iceberg", "catalog", "rest", "auth", "bearer", "token"},
	{"sink", "iceberg", "catalog", "rest", "auth", "oauth2", "client_secret"},
	{"sink", "iceberg", "catalog", "rest", "auth", "sigv4", "secret_access_key"},
	{"sink", "iceberg", "catalog", "rest", "auth", "sigv4", "session_token"},
	{"sink", "iceberg", "catalog", "s3tables", "secret_access_key"},
	{"sink", "iceberg", "catalog", "s3tables", "session_token"},
	{"sink", "iceberg", "catalog", "snowflake", "password"},
	{"sink", "iceberg", "catalog", "unity", "token"},
	{"sink", "iceberg", "storage_credentials", "azure", "account_key"},
	{"sink", "iceberg", "storage_credentials", "azure", "client_secret"},
	{"sink", "iceberg", "storage_credentials", "gcs", "credentials_json"},
	{"sink", "iceberg", "storage_credentials", "s3", "secret_access_key"},
	{"sink", "iceberg", "storage_credentials", "s3", "session_token"},
	{"sink", "iceberg", "write_mode", "merge_on_read", "index_backend", "slatedb", "object_store", "root_certificate_pem"},
	{"sink", "kafka", "connection", "auth", "password"},
	{"sink", "kafka", "connection", "auth", "ssl_key_password"},
	{"sink", "kafka", "format", "debezium", "format_config", "key_serde", "avro", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "debezium", "format_config", "key_serde", "avro", "schema_registry", "confluent", "password"},
	{"sink", "kafka", "format", "debezium", "format_config", "key_serde", "json", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "debezium", "format_config", "key_serde", "json", "schema_registry", "confluent", "password"},
	{"sink", "kafka", "format", "debezium", "format_config", "key_serde", "protobuf", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "debezium", "format_config", "key_serde", "protobuf", "schema_registry", "confluent", "password"},
	{"sink", "kafka", "format", "debezium", "format_config", "value_serde", "avro", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "debezium", "format_config", "value_serde", "avro", "schema_registry", "confluent", "password"},
	{"sink", "kafka", "format", "debezium", "format_config", "value_serde", "json", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "debezium", "format_config", "value_serde", "json", "schema_registry", "confluent", "password"},
	{"sink", "kafka", "format", "debezium", "format_config", "value_serde", "protobuf", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "debezium", "format_config", "value_serde", "protobuf", "schema_registry", "confluent", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "key_serde", "avro", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "key_serde", "avro", "schema_registry", "confluent", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "key_serde", "json", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "key_serde", "json", "schema_registry", "confluent", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "key_serde", "protobuf", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "key_serde", "protobuf", "schema_registry", "confluent", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "value_serde", "avro", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "value_serde", "avro", "schema_registry", "confluent", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "value_serde", "json", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "value_serde", "json", "schema_registry", "confluent", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "value_serde", "protobuf", "schema_registry", "apicurio", "password"},
	{"sink", "kafka", "format", "supermetal", "format_config", "value_serde", "protobuf", "schema_registry", "confluent", "password"},
	{"sink", "motherduck", "connection", "pg", "password"},
	{"sink", "motherduck", "connection", "pg", "ssl_cert"},
	{"sink", "motherduck", "connection", "pg", "ssl_key"},
	{"sink", "motherduck", "connection", "pg", "ssl_root_cert"},
	{"sink", "motherduck", "connection", "pg", "tunnel", "ssh", "auth", "bring_your_own_key", "private_key"},
	{"sink", "motherduck", "connection", "pg", "tunnel", "ssh", "auth", "generated_key", "private_key"},
	{"sink", "motherduck", "connection", "quack", "token"},
	{"sink", "postgres", "connection", "password"},
	{"sink", "postgres", "connection", "ssl_cert"},
	{"sink", "postgres", "connection", "ssl_key"},
	{"sink", "postgres", "connection", "ssl_root_cert"},
	{"sink", "postgres", "connection", "tunnel", "ssh", "auth", "bring_your_own_key", "private_key"},
	{"sink", "postgres", "connection", "tunnel", "ssh", "auth", "generated_key", "private_key"},
	{"sink", "redshift", "connection", "auth", "iam_credentials", "secret_access_key"},
	{"sink", "redshift", "connection", "auth", "iam_credentials", "session_token"},
	{"sink", "redshift", "connection", "auth", "password", "password"},
	{"sink", "redshift", "connection", "ssl_root_cert"},
	{"sink", "redshift", "connection", "tunnel", "ssh", "auth", "bring_your_own_key", "private_key"},
	{"sink", "redshift", "connection", "tunnel", "ssh", "auth", "generated_key", "private_key"},
	{"sink", "snowflake", "connection", "auth", "key_pair", "private_key_password"},
	{"sink", "snowflake", "connection", "auth", "key_pair", "private_key_pem"},
	{"sink", "snowflake", "connection", "auth", "password", "password"},
	{"sink", "webhook", "auth", "basic", "password"},
	{"sink", "webhook", "auth", "bearer", "token"},
	{"sink", "webhook", "auth", "header", "value"},
	{"sink", "webhook", "format", "debezium", "format_config", "key_serde", "avro", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "debezium", "format_config", "key_serde", "avro", "schema_registry", "confluent", "password"},
	{"sink", "webhook", "format", "debezium", "format_config", "key_serde", "json", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "debezium", "format_config", "key_serde", "json", "schema_registry", "confluent", "password"},
	{"sink", "webhook", "format", "debezium", "format_config", "key_serde", "protobuf", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "debezium", "format_config", "key_serde", "protobuf", "schema_registry", "confluent", "password"},
	{"sink", "webhook", "format", "debezium", "format_config", "value_serde", "avro", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "debezium", "format_config", "value_serde", "avro", "schema_registry", "confluent", "password"},
	{"sink", "webhook", "format", "debezium", "format_config", "value_serde", "json", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "debezium", "format_config", "value_serde", "json", "schema_registry", "confluent", "password"},
	{"sink", "webhook", "format", "debezium", "format_config", "value_serde", "protobuf", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "debezium", "format_config", "value_serde", "protobuf", "schema_registry", "confluent", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "key_serde", "avro", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "key_serde", "avro", "schema_registry", "confluent", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "key_serde", "json", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "key_serde", "json", "schema_registry", "confluent", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "key_serde", "protobuf", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "key_serde", "protobuf", "schema_registry", "confluent", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "value_serde", "avro", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "value_serde", "avro", "schema_registry", "confluent", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "value_serde", "json", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "value_serde", "json", "schema_registry", "confluent", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "value_serde", "protobuf", "schema_registry", "apicurio", "password"},
	{"sink", "webhook", "format", "supermetal", "format_config", "value_serde", "protobuf", "schema_registry", "confluent", "password"},
	{"source", "clickhouse", "catalog", "column_hashing", "shared_secret"},
	{"source", "clickhouse", "connection", "password"},
	{"source", "clickhouse", "connection", "ssl_client_cert_pem"},
	{"source", "clickhouse", "connection", "ssl_client_key_pem"},
	{"source", "clickhouse", "connection", "ssl_root_cert"},
	{"source", "db2", "catalog", "column_hashing", "shared_secret"},
	{"source", "db2", "connection", "password"},
	{"source", "file_source", "catalog", "column_hashing", "shared_secret"},
	{"source", "file_source", "object_store", "root_certificate_pem"},
	{"source", "mongo", "catalog", "column_hashing", "shared_secret"},
	{"source", "mongo", "connection", "password"},
	{"source", "mongo", "connection", "ssl_mode", "enable", "ca_file"},
	{"source", "mongo", "connection", "ssl_mode", "enable", "cert_key_file"},
	{"source", "mongo", "replication_type", "change_streams", "replication_mode", "schema_mode", "object_store", "root_certificate_pem"},
	{"source", "mongo", "replication_type", "snapshot", "replication_mode", "schema_mode", "object_store", "root_certificate_pem"},
	{"source", "mysql", "catalog", "column_hashing", "shared_secret"},
	{"source", "mysql", "connection", "password"},
	{"source", "mysql", "connection", "ssl_mode", "verify_ca", "ca_file"},
	{"source", "mysql", "connection", "ssl_mode", "verify_identity", "ca_file"},
	{"source", "mysql", "connection", "tunnel", "ssh", "auth", "bring_your_own_key", "private_key"},
	{"source", "mysql", "connection", "tunnel", "ssh", "auth", "generated_key", "private_key"},
	{"source", "oracle", "catalog", "column_hashing", "shared_secret"},
	{"source", "oracle", "connection", "password"},
	{"source", "postgres", "catalog", "column_hashing", "shared_secret"},
	{"source", "postgres", "connection", "password"},
	{"source", "postgres", "connection", "ssl_cert"},
	{"source", "postgres", "connection", "ssl_key"},
	{"source", "postgres", "connection", "ssl_root_cert"},
	{"source", "postgres", "connection", "tunnel", "ssh", "auth", "bring_your_own_key", "private_key"},
	{"source", "postgres", "connection", "tunnel", "ssh", "auth", "generated_key", "private_key"},
	{"source", "postgres", "replication_type", "query_based", "delete_tracking", "enabled", "pk_index_store", "root_certificate_pem"},
	{"source", "sqlserver", "catalog", "column_hashing", "shared_secret"},
	{"source", "sqlserver", "connection", "auth", "activedirectory", "token"},
	{"source", "sqlserver", "connection", "auth", "standard", "password"},
	{"source", "sqlserver", "connection", "auth", "windows", "password"},
	{"source", "sqlserver", "connection", "ssl_mode", "enable", "ca_file"},
	{"source", "sqlserver", "connection", "tunnel", "ssh", "auth", "bring_your_own_key", "private_key"},
	{"source", "sqlserver", "connection", "tunnel", "ssh", "auth", "generated_key", "private_key"},
}

type ConnectorModel struct {
	ID               types.String           `tfsdk:"id"`
	Name             types.String           `tfsdk:"name"`
	Disabled         types.Bool             `tfsdk:"disabled"`
	Source           *SourceModel           `tfsdk:"source"`
	Sink             *SinkModel             `tfsdk:"sink"`
	Buffer           *BufferModel           `tfsdk:"buffer"`
	IdentifierNaming *IdentifierNamingModel `tfsdk:"identifier_naming"`
	Limits           *LimitsModel           `tfsdk:"limits"`
	Schedule         *ScheduleModel         `tfsdk:"schedule"`
}

func connectorEnvelopeAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"buffer": schema.SingleNestedAttribute{
			Optional:   true,
			Attributes: BufferAttributes(),
		},
		"identifier_naming": schema.SingleNestedAttribute{
			Optional:   true,
			Attributes: IdentifierNamingAttributes(),
		},
		"limits": schema.SingleNestedAttribute{
			Optional:   true,
			Attributes: LimitsAttributes(),
		},
		"schedule": schema.SingleNestedAttribute{
			Optional:   true,
			Attributes: ScheduleAttributes(),
		},
	}
}

type SourceModel struct {
	Clickhouse *ClickhouseSourceModel `tfsdk:"clickhouse"`
	Db2        *Db2SourceModel        `tfsdk:"db2"`
	FileSource *FileSourceModel       `tfsdk:"file_source"`
	Mongo      *MongoSourceModel      `tfsdk:"mongo"`
	Mysql      *MySqlSourceModel      `tfsdk:"mysql"`
	Oracle     *OracleSourceModel     `tfsdk:"oracle"`
	Postgres   *PostgresSourceModel   `tfsdk:"postgres"`
	Sqlserver  *SqlServerSourceModel  `tfsdk:"sqlserver"`
}

type SinkModel struct {
	BigQuery   *BigQuerySinkModel   `tfsdk:"big_query"`
	Clickhouse *ClickhouseSinkModel `tfsdk:"clickhouse"`
	Databricks *DatabricksSinkModel `tfsdk:"databricks"`
	Doris      *DorisSinkModel      `tfsdk:"doris"`
	Duckdb     *DuckDBSinkModel     `tfsdk:"duckdb"`
	FileSink   *FileSinkModel       `tfsdk:"file_sink"`
	Iceberg    *IcebergSinkModel    `tfsdk:"iceberg"`
	Kafka      *KafkaSinkModel      `tfsdk:"kafka"`
	Motherduck *DuckDBSinkModel     `tfsdk:"motherduck"`
	Postgres   *PostgresSinkModel   `tfsdk:"postgres"`
	Redshift   *RedshiftSinkModel   `tfsdk:"redshift"`
	Snowflake  *SnowflakeSinkModel  `tfsdk:"snowflake"`
	Webhook    *WebhookSinkModel    `tfsdk:"webhook"`
}

func sourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"clickhouse": schema.SingleNestedAttribute{
			MarkdownDescription: "ClickHouse replication source",
			Optional:            true,
			Attributes:          clickhouseSourceAttributes(),
		},
		"db2": schema.SingleNestedAttribute{
			MarkdownDescription: "Db2 replication source",
			Optional:            true,
			Attributes:          db2SourceAttributes(),
		},
		"file_source": schema.SingleNestedAttribute{
			MarkdownDescription: "Ingest files from object stores (S3, GCS, Azure Blob) or filesystems (local, SFTP)",
			Optional:            true,
			Attributes:          fileSourceAttributes(),
		},
		"mongo": schema.SingleNestedAttribute{
			MarkdownDescription: "MongoDB replication source",
			Optional:            true,
			Attributes:          mongoSourceAttributes(),
		},
		"mysql": schema.SingleNestedAttribute{
			MarkdownDescription: "MySQL replication source",
			Optional:            true,
			Attributes:          mysqlSourceAttributes(),
		},
		"oracle": schema.SingleNestedAttribute{
			MarkdownDescription: "Oracle replication source",
			Optional:            true,
			Attributes:          oracleSourceAttributes(),
		},
		"postgres": schema.SingleNestedAttribute{
			MarkdownDescription: "PostgreSQL replication source",
			Optional:            true,
			Attributes:          postgresSourceAttributes(),
		},
		"sqlserver": schema.SingleNestedAttribute{
			MarkdownDescription: "SQL Server replication source",
			Optional:            true,
			Attributes:          sqlserverSourceAttributes(),
		},
	}
}

func sinkAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"big_query": schema.SingleNestedAttribute{
			MarkdownDescription: "BigQuery destination",
			Optional:            true,
			Attributes:          bigquerySinkAttributes(),
		},
		"clickhouse": schema.SingleNestedAttribute{
			MarkdownDescription: "Configuration for a ClickHouse data sink",
			Optional:            true,
			Attributes:          clickhouseSinkAttributes(),
		},
		"databricks": schema.SingleNestedAttribute{
			MarkdownDescription: "Databricks destination",
			Optional:            true,
			Attributes:          databricksSinkAttributes(),
		},
		"doris": schema.SingleNestedAttribute{
			MarkdownDescription: "Apache Doris sink configuration",
			Optional:            true,
			Attributes:          dorisSinkAttributes(),
		},
		"duckdb": schema.SingleNestedAttribute{
			MarkdownDescription: "DuckDB sink",
			Optional:            true,
			Attributes:          duckdbSinkAttributes(),
		},
		"file_sink": schema.SingleNestedAttribute{
			MarkdownDescription: "Writes snapshot and CDC rows as files in object storage like S3/ABS/GCS etc.",
			Optional:            true,
			Attributes:          fileSinkAttributes(),
		},
		"iceberg": schema.SingleNestedAttribute{
			MarkdownDescription: "Iceberg destination",
			Optional:            true,
			Attributes:          icebergSinkAttributes(),
		},
		"kafka": schema.SingleNestedAttribute{
			MarkdownDescription: "Kafka destination",
			Optional:            true,
			Attributes:          kafkaSinkAttributes(),
		},
		"motherduck": schema.SingleNestedAttribute{
			MarkdownDescription: "DuckDB sink",
			Optional:            true,
			Attributes:          duckdbSinkAttributes(),
		},
		"postgres": schema.SingleNestedAttribute{
			MarkdownDescription: "PostgreSQL destination",
			Optional:            true,
			Attributes:          postgresSinkAttributes(),
		},
		"redshift": schema.SingleNestedAttribute{
			MarkdownDescription: "Amazon Redshift destination",
			Optional:            true,
			Attributes:          redshiftSinkAttributes(),
		},
		"snowflake": schema.SingleNestedAttribute{
			MarkdownDescription: "Snowflake destination",
			Optional:            true,
			Attributes:          snowflakeSinkAttributes(),
		},
		"webhook": schema.SingleNestedAttribute{
			MarkdownDescription: "Webhook destination",
			Optional:            true,
			Attributes:          webhookSinkAttributes(),
		},
	}
}

func (m *SourceModel) toAPI() (api.ConnectorSource, diag.Diagnostics) {
	var source api.ConnectorSource
	var diags diag.Diagnostics

	if m.Clickhouse != nil {
		inner, d := m.Clickhouse.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource7{Clickhouse: inner}
		if err := source.FromConnectorSource7(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.Db2 != nil {
		inner, d := m.Db2.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource6{Db2: inner}
		if err := source.FromConnectorSource6(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.FileSource != nil {
		inner, d := m.FileSource.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource5{FileSource: inner}
		if err := source.FromConnectorSource5(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.Mongo != nil {
		inner, d := m.Mongo.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource3{Mongo: inner}
		if err := source.FromConnectorSource3(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.Mysql != nil {
		inner, d := m.Mysql.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource2{Mysql: inner}
		if err := source.FromConnectorSource2(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.Oracle != nil {
		inner, d := m.Oracle.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource4{Oracle: inner}
		if err := source.FromConnectorSource4(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.Postgres != nil {
		inner, d := m.Postgres.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource0{Postgres: inner}
		if err := source.FromConnectorSource0(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	} else if m.Sqlserver != nil {
		inner, d := m.Sqlserver.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return source, diags
		}
		wrapper := api.ConnectorSource1{Sqlserver: inner}
		if err := source.FromConnectorSource1(wrapper); err != nil {
			diags.AddError("Failed to set source", err.Error())
			return source, diags
		}
	}
	return source, diags
}

func (m *SinkModel) toAPI() (api.ConnectorSink, diag.Diagnostics) {
	var sink api.ConnectorSink
	var diags diag.Diagnostics

	if m.BigQuery != nil {
		inner, d := m.BigQuery.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink11{BigQuery: inner}
		if err := sink.FromConnectorSink11(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Clickhouse != nil {
		inner, d := m.Clickhouse.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink1{Clickhouse: inner}
		if err := sink.FromConnectorSink1(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Databricks != nil {
		inner, d := m.Databricks.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink5{Databricks: inner}
		if err := sink.FromConnectorSink5(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Doris != nil {
		inner, d := m.Doris.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink8{Doris: inner}
		if err := sink.FromConnectorSink8(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Duckdb != nil {
		inner, d := m.Duckdb.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink9{Duckdb: inner}
		if err := sink.FromConnectorSink9(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.FileSink != nil {
		inner, d := m.FileSink.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink12{FileSink: inner}
		if err := sink.FromConnectorSink12(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Iceberg != nil {
		inner, d := m.Iceberg.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink7{Iceberg: inner}
		if err := sink.FromConnectorSink7(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Kafka != nil {
		inner, d := m.Kafka.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink4{Kafka: inner}
		if err := sink.FromConnectorSink4(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Motherduck != nil {
		inner, d := m.Motherduck.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink10{Motherduck: inner}
		if err := sink.FromConnectorSink10(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Postgres != nil {
		inner, d := m.Postgres.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink0{Postgres: inner}
		if err := sink.FromConnectorSink0(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Redshift != nil {
		inner, d := m.Redshift.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink13{Redshift: inner}
		if err := sink.FromConnectorSink13(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Snowflake != nil {
		inner, d := m.Snowflake.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink2{Snowflake: inner}
		if err := sink.FromConnectorSink2(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	} else if m.Webhook != nil {
		inner, d := m.Webhook.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return sink, diags
		}
		wrapper := api.ConnectorSink6{Webhook: inner}
		if err := sink.FromConnectorSink6(wrapper); err != nil {
			diags.AddError("Failed to set sink", err.Error())
			return sink, diags
		}
	}
	return sink, diags
}

func (m *SourceModel) mergeFromAPI(source api.ConnectorSource, state *SourceModel) {
	if state == m {
		stateCopy := *state
		state = &stateCopy
	}
	*m = SourceModel{}
	variantJSON, _ := json.Marshal(source)
	var variantKeys map[string]json.RawMessage
	_ = json.Unmarshal(variantJSON, &variantKeys)

	if _, ok := variantKeys["clickhouse"]; ok {
		v, err := source.AsConnectorSource7()
		if err != nil {
			return
		}
		if m.Clickhouse == nil {
			m.Clickhouse = &ClickhouseSourceModel{}
		}
		var st *ClickhouseSourceModel
		if state != nil {
			st = state.Clickhouse
		}
		m.Clickhouse.mergeFromAPI(v.Clickhouse, st)
	}
	if _, ok := variantKeys["db2"]; ok {
		v, err := source.AsConnectorSource6()
		if err != nil {
			return
		}
		if m.Db2 == nil {
			m.Db2 = &Db2SourceModel{}
		}
		var st *Db2SourceModel
		if state != nil {
			st = state.Db2
		}
		m.Db2.mergeFromAPI(v.Db2, st)
	}
	if _, ok := variantKeys["file_source"]; ok {
		v, err := source.AsConnectorSource5()
		if err != nil {
			return
		}
		if m.FileSource == nil {
			m.FileSource = &FileSourceModel{}
		}
		var st *FileSourceModel
		if state != nil {
			st = state.FileSource
		}
		m.FileSource.mergeFromAPI(v.FileSource, st)
	}
	if _, ok := variantKeys["mongo"]; ok {
		v, err := source.AsConnectorSource3()
		if err != nil {
			return
		}
		if m.Mongo == nil {
			m.Mongo = &MongoSourceModel{}
		}
		var st *MongoSourceModel
		if state != nil {
			st = state.Mongo
		}
		m.Mongo.mergeFromAPI(v.Mongo, st)
	}
	if _, ok := variantKeys["mysql"]; ok {
		v, err := source.AsConnectorSource2()
		if err != nil {
			return
		}
		if m.Mysql == nil {
			m.Mysql = &MySqlSourceModel{}
		}
		var st *MySqlSourceModel
		if state != nil {
			st = state.Mysql
		}
		m.Mysql.mergeFromAPI(v.Mysql, st)
	}
	if _, ok := variantKeys["oracle"]; ok {
		v, err := source.AsConnectorSource4()
		if err != nil {
			return
		}
		if m.Oracle == nil {
			m.Oracle = &OracleSourceModel{}
		}
		var st *OracleSourceModel
		if state != nil {
			st = state.Oracle
		}
		m.Oracle.mergeFromAPI(v.Oracle, st)
	}
	if _, ok := variantKeys["postgres"]; ok {
		v, err := source.AsConnectorSource0()
		if err != nil {
			return
		}
		if m.Postgres == nil {
			m.Postgres = &PostgresSourceModel{}
		}
		var st *PostgresSourceModel
		if state != nil {
			st = state.Postgres
		}
		m.Postgres.mergeFromAPI(v.Postgres, st)
	}
	if _, ok := variantKeys["sqlserver"]; ok {
		v, err := source.AsConnectorSource1()
		if err != nil {
			return
		}
		if m.Sqlserver == nil {
			m.Sqlserver = &SqlServerSourceModel{}
		}
		var st *SqlServerSourceModel
		if state != nil {
			st = state.Sqlserver
		}
		m.Sqlserver.mergeFromAPI(v.Sqlserver, st)
	}
}

func (m *SinkModel) mergeFromAPI(sink api.ConnectorSink, state *SinkModel) {
	if state == m {
		stateCopy := *state
		state = &stateCopy
	}
	*m = SinkModel{}
	variantJSON, _ := json.Marshal(sink)
	var variantKeys map[string]json.RawMessage
	_ = json.Unmarshal(variantJSON, &variantKeys)

	if _, ok := variantKeys["big_query"]; ok {
		v, err := sink.AsConnectorSink11()
		if err != nil {
			return
		}
		if m.BigQuery == nil {
			m.BigQuery = &BigQuerySinkModel{}
		}
		var st *BigQuerySinkModel
		if state != nil {
			st = state.BigQuery
		}
		m.BigQuery.mergeFromAPI(v.BigQuery, st)
	}
	if _, ok := variantKeys["clickhouse"]; ok {
		v, err := sink.AsConnectorSink1()
		if err != nil {
			return
		}
		if m.Clickhouse == nil {
			m.Clickhouse = &ClickhouseSinkModel{}
		}
		var st *ClickhouseSinkModel
		if state != nil {
			st = state.Clickhouse
		}
		m.Clickhouse.mergeFromAPI(v.Clickhouse, st)
	}
	if _, ok := variantKeys["databricks"]; ok {
		v, err := sink.AsConnectorSink5()
		if err != nil {
			return
		}
		if m.Databricks == nil {
			m.Databricks = &DatabricksSinkModel{}
		}
		var st *DatabricksSinkModel
		if state != nil {
			st = state.Databricks
		}
		m.Databricks.mergeFromAPI(v.Databricks, st)
	}
	if _, ok := variantKeys["doris"]; ok {
		v, err := sink.AsConnectorSink8()
		if err != nil {
			return
		}
		if m.Doris == nil {
			m.Doris = &DorisSinkModel{}
		}
		var st *DorisSinkModel
		if state != nil {
			st = state.Doris
		}
		m.Doris.mergeFromAPI(v.Doris, st)
	}
	if _, ok := variantKeys["duckdb"]; ok {
		v, err := sink.AsConnectorSink9()
		if err != nil {
			return
		}
		if m.Duckdb == nil {
			m.Duckdb = &DuckDBSinkModel{}
		}
		var st *DuckDBSinkModel
		if state != nil {
			st = state.Duckdb
		}
		m.Duckdb.mergeFromAPI(v.Duckdb, st)
	}
	if _, ok := variantKeys["file_sink"]; ok {
		v, err := sink.AsConnectorSink12()
		if err != nil {
			return
		}
		if m.FileSink == nil {
			m.FileSink = &FileSinkModel{}
		}
		var st *FileSinkModel
		if state != nil {
			st = state.FileSink
		}
		m.FileSink.mergeFromAPI(v.FileSink, st)
	}
	if _, ok := variantKeys["iceberg"]; ok {
		v, err := sink.AsConnectorSink7()
		if err != nil {
			return
		}
		if m.Iceberg == nil {
			m.Iceberg = &IcebergSinkModel{}
		}
		var st *IcebergSinkModel
		if state != nil {
			st = state.Iceberg
		}
		m.Iceberg.mergeFromAPI(v.Iceberg, st)
	}
	if _, ok := variantKeys["kafka"]; ok {
		v, err := sink.AsConnectorSink4()
		if err != nil {
			return
		}
		if m.Kafka == nil {
			m.Kafka = &KafkaSinkModel{}
		}
		var st *KafkaSinkModel
		if state != nil {
			st = state.Kafka
		}
		m.Kafka.mergeFromAPI(v.Kafka, st)
	}
	if _, ok := variantKeys["motherduck"]; ok {
		v, err := sink.AsConnectorSink10()
		if err != nil {
			return
		}
		if m.Motherduck == nil {
			m.Motherduck = &DuckDBSinkModel{}
		}
		var st *DuckDBSinkModel
		if state != nil {
			st = state.Motherduck
		}
		m.Motherduck.mergeFromAPI(v.Motherduck, st)
	}
	if _, ok := variantKeys["postgres"]; ok {
		v, err := sink.AsConnectorSink0()
		if err != nil {
			return
		}
		if m.Postgres == nil {
			m.Postgres = &PostgresSinkModel{}
		}
		var st *PostgresSinkModel
		if state != nil {
			st = state.Postgres
		}
		m.Postgres.mergeFromAPI(v.Postgres, st)
	}
	if _, ok := variantKeys["redshift"]; ok {
		v, err := sink.AsConnectorSink13()
		if err != nil {
			return
		}
		if m.Redshift == nil {
			m.Redshift = &RedshiftSinkModel{}
		}
		var st *RedshiftSinkModel
		if state != nil {
			st = state.Redshift
		}
		m.Redshift.mergeFromAPI(v.Redshift, st)
	}
	if _, ok := variantKeys["snowflake"]; ok {
		v, err := sink.AsConnectorSink2()
		if err != nil {
			return
		}
		if m.Snowflake == nil {
			m.Snowflake = &SnowflakeSinkModel{}
		}
		var st *SnowflakeSinkModel
		if state != nil {
			st = state.Snowflake
		}
		m.Snowflake.mergeFromAPI(v.Snowflake, st)
	}
	if _, ok := variantKeys["webhook"]; ok {
		v, err := sink.AsConnectorSink6()
		if err != nil {
			return
		}
		if m.Webhook == nil {
			m.Webhook = &WebhookSinkModel{}
		}
		var st *WebhookSinkModel
		if state != nil {
			st = state.Webhook
		}
		m.Webhook.mergeFromAPI(v.Webhook, st)
	}
}

func (m *ConnectorModel) toAPIConnector() (api.ConnectorConnector, diag.Diagnostics) {
	var diags diag.Diagnostics

	connector := api.ConnectorConnector{
		Id:       m.ID.ValueString(),
		Name:     m.Name.ValueStringPointer(),
		Disabled: m.Disabled.ValueBoolPointer(),
	}

	if m.Source != nil {
		source, d := m.Source.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return connector, diags
		}
		connector.Source = source
	}

	if m.Sink != nil {
		sink, d := m.Sink.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return connector, diags
		}
		connector.Sink = sink
	}

	if m.Buffer != nil {
		inner, d := m.Buffer.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return connector, diags
		}
		connector.Buffer = &inner
	}

	if m.IdentifierNaming != nil {
		inner, d := m.IdentifierNaming.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return connector, diags
		}
		connector.IdentifierNaming = &inner
	}

	if m.Limits != nil {
		inner, d := m.Limits.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return connector, diags
		}
		connector.Limits = &inner
	}

	if m.Schedule != nil {
		inner, d := m.Schedule.toAPI()
		diags.Append(d...)
		if diags.HasError() {
			return connector, diags
		}
		connector.Schedule = &inner
	}

	return connector, diags
}

func (m *ConnectorModel) mergeFromAPI(connector api.ConnectorConnector, state *ConnectorModel) {
	if state == m {
		stateCopy := *state
		state = &stateCopy
	}
	*m = ConnectorModel{}
	m.ID = types.StringValue(connector.Id)

	if connector.Name != nil {
		m.Name = types.StringValue(*connector.Name)
	} else {
		m.Name = types.StringNull()
	}

	if connector.Disabled != nil {
		m.Disabled = types.BoolValue(*connector.Disabled)
	} else {
		m.Disabled = types.BoolNull()
	}

	if connector.Buffer != nil {
		m.Buffer = &BufferModel{}
		var st *BufferModel
		if state != nil {
			st = state.Buffer
		}
		m.Buffer.mergeFromAPI(*connector.Buffer, st)
	}

	if connector.IdentifierNaming != nil {
		m.IdentifierNaming = &IdentifierNamingModel{}
		var st *IdentifierNamingModel
		if state != nil {
			st = state.IdentifierNaming
		}
		m.IdentifierNaming.mergeFromAPI(*connector.IdentifierNaming, st)
	}

	if connector.Limits != nil {
		m.Limits = &LimitsModel{}
		var st *LimitsModel
		if state != nil {
			st = state.Limits
		}
		m.Limits.mergeFromAPI(*connector.Limits, st)
	}

	if connector.Schedule != nil {
		m.Schedule = &ScheduleModel{}
		var st *ScheduleModel
		if state != nil {
			st = state.Schedule
		}
		m.Schedule.mergeFromAPI(*connector.Schedule, st)
	}

	if m.Source == nil {
		m.Source = &SourceModel{}
	}
	var stateSource *SourceModel
	if state != nil {
		stateSource = state.Source
	}
	m.Source.mergeFromAPI(connector.Source, stateSource)

	if m.Sink == nil {
		m.Sink = &SinkModel{}
	}
	var stateSink *SinkModel
	if state != nil {
		stateSink = state.Sink
	}
	m.Sink.mergeFromAPI(connector.Sink, stateSink)
}

func countSourceVariants(m *SourceModel) int {
	if m == nil {
		return 0
	}
	count := 0
	if m.Clickhouse != nil {
		count++
	}
	if m.Db2 != nil {
		count++
	}
	if m.FileSource != nil {
		count++
	}
	if m.Mongo != nil {
		count++
	}
	if m.Mysql != nil {
		count++
	}
	if m.Oracle != nil {
		count++
	}
	if m.Postgres != nil {
		count++
	}
	if m.Sqlserver != nil {
		count++
	}
	return count
}

func countSinkVariants(m *SinkModel) int {
	if m == nil {
		return 0
	}
	count := 0
	if m.BigQuery != nil {
		count++
	}
	if m.Clickhouse != nil {
		count++
	}
	if m.Databricks != nil {
		count++
	}
	if m.Doris != nil {
		count++
	}
	if m.Duckdb != nil {
		count++
	}
	if m.FileSink != nil {
		count++
	}
	if m.Iceberg != nil {
		count++
	}
	if m.Kafka != nil {
		count++
	}
	if m.Motherduck != nil {
		count++
	}
	if m.Postgres != nil {
		count++
	}
	if m.Redshift != nil {
		count++
	}
	if m.Snowflake != nil {
		count++
	}
	if m.Webhook != nil {
		count++
	}
	return count
}
